### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by roylan34** [electron-vite/electron-vite-react#102]
I want to send data from main process to renderer so I `import {contextBridge} from "electron" `and used `contextBridge.exposeInMainWorld("data", "Test")`.

And I enabled `contextIsolation:true` in file `electron/main/index.ts`  but it cause the error as seen in image below.

![require undefined](https://user-images.githubusercontent.com/12495362/213337711-dfb15f72-076e-4b35-af8c-fee38345c10b.png)

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-react#-be-aware
