### ISSUE TITLE
Cannot use  `import {app} from 'electron'` from files under `src` folder

### ISSUE THREAD

**Issue by alexsunseeker** [electron-vite/electron-vite-react#105]
Hi, Thanks for this awesome boilerplate you bring us! I just ran into an issue when I tried to import `app` from files under the `src` folder.
<img width="704" alt="image" src="https://user-images.githubusercontent.com/110548476/213365947-6e1c9122-b484-4252-a022-ffa717a07331.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/110548476/213366018-b293f53f-8605-4ae7-a36d-201db95ca140.png">

The error shows `electron' does not provide an export named 'app'` 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/110548476/213366267-d3864926-d2b4-4857-843d-de804fbf19f6.png">

But it works fine from `electron/main/index.ts`, Does anyone can help me? Thanks!

**Comment by alexsunseeker** [comment]
Seems that render process has to call Electron API via IPC

**Comment by shifenhutu** [comment]
did you fix it ?  please share it
