### ISSUE TITLE
Alias resolution not working in exe build and giving unexpected errors.

### ISSUE THREAD

**Issue by developer-choice124** [electron-vite/electron-vite-react#106]
![image](https://user-images.githubusercontent.com/78584756/214577595-ce6a1283-ebc6-4208-ba9d-7373d9dfdc3c.png)
![image](https://user-images.githubusercontent.com/78584756/214577724-0dbbe51a-5ec9-44af-8bd6-7b93e7c9cf9a.png)
**I am getting these errors only if I am using these configurations in my vite.config.ts & tsconfig.json files, if I remove them then exe build works as expected no issues. I am adding these configurations so I can use alias names on my import statements rather than using the actual whole path which may lead to errors**

For an instance, we usually do like this if I want to import my service from services folder inside src folder
`import { templateService } from './src/services';`
But I am doing 
`import { templateService } from '@services';`
Which makes it handy doesn't matter what is depth or where we are in the project.

My electron-builder.json5 file is default one provided by this project so not including that. Please let me know if more explaination is needed.

OS & Environment
OS: windows 10
yarn: 1.22.19
node: v18.12.1

My tsconfig.json file is as follows - 
[tsconfig.json](https://pastebin.com/EH6eSNM6)

and vite.config.ts as -
[vite.config.ts](https://pastebin.com/3HhuYyU6)

**Comment by caoxiemeihao** [comment]
`services/index`
