### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by pastinepolenta** [electron-vite/electron-vite-react#107]
I get an error in the browser `__dirname is not defined` when running with 
```
nodeIntegration: false,
contextIsolation: true,
```

and I commented out the `renderer` in vite.config

Is there anything else to do to make it work safely?

**Comment by caoxiemeihao** [comment]
`import.meta.url`

**Comment by pastinepolenta** [comment]
sorry what is this? in which file am I supposed to put that import?
The error is in the electron file

```
Uncaught ReferenceError: __dirname is not defined
    at node_modules/electron/index.js
```

Seem related to this: https://github.com/electron/electron/issues/24005

**Comment by caoxiemeihao** [comment]
Are you using Electron or Node.js-related APIs in your Renderer Process?

**Comment by RSS1102** [comment]
@pastinepolenta  you can see it :https://blog.logrocket.com/alternatives-dirname-node-js-es-modules/ .

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-plugin-electron-renderer/issues/24

**Comment by dealdot** [comment]
> I get an error in the browser `__dirname is not defined` when running with
> 
> ```
> nodeIntegration: false,
> contextIsolation: true,
> ```
> 
> and I commented out the `renderer` in vite.config
> 
> Is there anything else to do to make it work safely?

hello, I have the same problem, how did you resolve it in the end? thanks

**Comment by TEParsons** [comment]
For anyone else confused (as I was) by @caoxiemeihao's answer: You need to replace `__dirname` with `import.meta.url` in wherever the source of the error is. 

In my case, I was using [this tutorial](https://dev.to/o_a_e/getting-started-with-electron-and-svelte-2gn8) and needed to replace `__dirname` on line 15 of `election.js`.
