### ISSUE TITLE
How to import file as raw string in electron folder ?

### ISSUE THREAD

**Issue by xia0hj** [electron-vite/electron-vite-react#110]
I want to import a file as string in electron folder like this:
```js
import initSql from './sql/init.sql?raw';
```
But I get error: `Error: Cannot find module './sql/init.sql?raw'`

**Comment by caoxiemeihao** [comment]
<img width="810" alt="image" src="https://user-images.githubusercontent.com/26263658/218223343-e4967d60-2d6b-4d5b-8997-5dde330cce73.png">
