### ISSUE TITLE
feat : Whether to add 'electron-updater' to the template to provide the option of minimum automatic update.

### ISSUE THREAD

**Issue by RSS1102** [electron-vite/electron-vite-react#111]
Whether an optional file should be added to the template to provide` electron-updater` update function.

**Comment by caoxiemeihao** [comment]
Not sure if it's a necessary feature and would add complexity to the tempalte.

**Comment by RSS1102** [comment]
> 
I also have this concern, but it can be used as an optional entry. By changing whether the variable is enabled, it is not enabled by default, so that it does not exist when the function is not enabled (of course, I am not sure whether this is reasonable)

**Comment by RSS1102** [comment]
> 需要评估使用人数，比如[Electron Forge](https://www.electronforge.io/)是否提供这个功能？

I saw it, but should we use it [electron.build](https://www.electron.build/auto-update )What about? After all, it is currently used for package of programs.

Is it necessary to introduce another dependency to do this? I don't know much about the mechanism of Mac.

**Comment by RSS1102** [comment]
[eletron-update-demo](https://github.com/RSS1102/eletron-update-demo), I used  [electron.build](https://www.electron.build/auto-update) to update the function, but I don't know whether it is a necessary function

**Comment by caoxiemeihao** [comment]
This looks great 👍, but `antd` may not be waht the user needs, can the update UI be implemented using raw HTML?

**Comment by RSS1102** [comment]
> 这看起来不错👍，但`antd`可能不是用户需要的，更新 UI 可以使用原始 HTML 实现吗？

I know. I will give them separately in the near future [electron-vite-react](https://github.com/electron-vite/electron-vite-react) and [electron-vite-vue](https://github.com/electron-vite/electron-vite-vue)One pr.

**Comment by caoxiemeihao** [comment]
Thanks for the plan, `electron-vite-vue` is not going to receive new PR for now, because it gets complicated.
I agree that it appears in `electron-vite-react`.

**Comment by RSS1102** [comment]
> 感谢您的计划，`electron-vite-vue`现在不会收到新的 PR，因为它变得复杂了。 我同意将其添加到`electron-vite-react`

ok, i get it.

**Comment by caoxiemeihao** [comment]
#123
