### ISSUE TITLE
Clarification on Template

### ISSUE THREAD

**Issue by GimpMaster** [electron-vite/electron-vite-react#113]
First of all thank you for this template. It really does help.

My question is that is seems the whole purpose of the tsconfig.json and tsconfig.node.json is just for linting and IDE?

 When running:

`yarn dev => vite`
and
`yarn build => tsc && vite build && electron-builder"

since tsconfig.json has noEmit: true, vite is the only thing that is emitting any output to the dist,dist-electron folders.

Is this correct?

**Comment by caoxiemeihao** [comment]
Yes

**Comment by GimpMaster** [comment]
Thank you.
