### ISSUE TITLE
Preload import error

### ISSUE THREAD

**Issue by uwemneku** [electron-vite/electron-vite-react#115]
I switched off node integration, but whenever I try importing anthing into the preload script I get an error,

![image](https://user-images.githubusercontent.com/30045115/220610819-a19c1b39-4466-488e-8ab2-d68b3b8ccf65.png)
I have certain functions decleared in a folder but whenever I import and use them in the preload script, an error is thrown in the browser console

**Comment by caoxiemeihao** [comment]
I saw the error and I'm considering build the Preload script as a bundle, but it will cause performance degradation.

- [ ] TODO

**Comment by caoxiemeihao** [comment]
1. Pull the latest commit.
2. Modify `scripts` config of `package.json`

```diff
{
  "scripts": {
-   "dev": "vite",
-   "build": "tsc && vite build && electron-builder",
+   "dev": "vite -c vite.legacy.config.ts",
+   "build": "tsc && vite build -c vite.legacy.config.ts && electron-builder",
  }
}
```

**Comment by umerjaved178** [comment]
@caoxiemeihao there is no legacy file in the latest version and it is preload is not exposing window objects

**Comment by caoxiemeihao** [comment]
@umerjaved178 at the latest commit, we just need `vite.config.ts`, `legacy` has been deprecated.
Can you encounter some error in your project?
