### ISSUE TITLE
Assigning ipcMain.on to a variable causes the app to crash

### ISSUE THREAD

**Issue by uwemneku** [electron-vite/electron-vite-react#116]
Hi, thanks again for this awesome template. 

I'm trying to add type definations to the `on` function of ipMain by type casting ipcMain.on and assigning it to a new variable

```ts
    cost customFunction = ipcMain.on as CustomFuctionType

    //this works fine
    ipMain.on('_test", ()=>{
    
    })
    
     //this throws an error
     customFunction("test", ()=>{
    })
```

Whenever I use `customFunction`, I get an error saying  `Cannot read properties of undefined (reading '_events')`
![image](https://user-images.githubusercontent.com/30045115/221376409-fcb088df-7be4-43c1-9013-2ee67d0df9b6.png)
but everything works fine when I call ipcMain.on

I noticed that if I bind the function to `this` in the same file where the custom function is called, everthing works fine
```ts
    cost customFunction = ipcMain.on.bind(this) as CustomFuctionType
    // works fine
    customFunction("test", ()=>{
    .///////
    })
```

But if `customFunction` is imported to a file, the same error is thrown when I try to use it even after binding it to `this`

Enviroment
node: v16.13.1
npm: 8.14.0

Package.json
  "devDependencies": {
    "@playwright/test": "^1.31.0",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@vitejs/plugin-react": "^3.1.0",
    "electron": "^23.1.1",
    "electron-builder": "^23.6.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sass": "^1.58.3",
    "typescript": "^4.9.5",
    "vite": "^4.1.4",
    "vite-electron-plugin": "^0.8.2",
    "vite-plugin-electron": "^0.11.1",
    "vite-plugin-electron-renderer": "^0.12.1"
  },

**Comment by caoxiemeihao** [comment]
```ts
export function customFunction(channel: string, listener: (event: IpcMainEvent, ...args: any[]) => void) {
  ipcMain.on(channel, listener)
}
```
