### ISSUE TITLE
[help]:electron-builder.json5中如何使process.env变量

### ISSUE THREAD

**Issue by huanglong6828** [electron-vite/electron-vite-react#118]
需求：打包时根据不同环境，调整app名称和环境后缀（比如：appname-loacl-version，appname2-prod-version）.
请教一下是否有合适的方案。

**Comment by huanglong6828** [comment]
![image](https://user-images.githubusercontent.com/19216952/222040718-9f212e4d-1bc5-4a34-8013-47f6fa88816f.png)
![image](https://user-images.githubusercontent.com/19216952/222040773-3a4ca933-5cf5-4445-a199-198f2b63150c.png)

**Comment by caoxiemeihao** [comment]
考虑使用 `electron-builder` 的 Node.js API 方式
