### ISSUE TITLE
Opening multiple windows using react router v6.8.1

### ISSUE THREAD

**Issue by agf2000** [electron-vite/electron-vite-react#120]
Would anyone please show how to implement opening multiple windows?

Under development I can open an about screen on a new electron window using createHashRouter.

if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
childWindow.loadURL(process.env['ELECTRON_RENDERER_URL']);
} else {
childWindow.loadFile(join(__dirname, '../renderer/index.html'));
}

But in production I get a blank screen.

I appreciate any help. Thanks!

-Ari

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by agf2000** [comment]
> Can you provide a minimal reproduction repo?

Sure thing. thank you!

https://github.com/agf2000/my-vite-react-electron-app.git

**Comment by caoxiemeihao** [comment]
https://github.com/alex8088/electron-vite
You should submit your question in this repository, it has nothing to do with me and I resent it
