### ISSUE TITLE
Uncaught ReferenceError: require is not defined,无法使用Electron contextBridge

### ISSUE THREAD

**Issue by Qyw-a** [electron-vite/electron-vite-react#124]
问题：
我想使用 contextBridge 这个功能
此时我在main.js 中开启了  contextIsolation: true这个设置

```
main.js
win = new BrowserWindow({
    show: false, // 创建时不显示窗口
    title: 'Main window',
    icon: join(process.env.PUBLIC, 'vite.svg'),
    webPreferences: {
      preload,
      nodeIntegration: true,
      contextIsolation: true,
    },
  })
```

我在preload.js中 使用contextBridge 

```
const { contextBridge } = require('electron')
contextBridge.exposeInMainWorld(
  'electron',
  {
    doThing: () => console.log('doing something')
  }
)
```
此时控制台会报错 ，require is not defined
请问如何处理这个问题

**Comment by caoxiemeihao** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/26263658/224598929-562833cb-42b4-4068-ab7d-50be1a58a17b.png">
把这个去掉，简单问题自己好好排查下。

**Comment by 2811267153** [comment]
> <img alt="image" width="631" src="https://user-images.githubusercontent.com/26263658/224598929-562833cb-42b4-4068-ab7d-50be1a58a17b.png">
> 
> 把这个去掉，简单问题自己好好排查下。

我想我应该早点来这里找答案的😢😢😢

**Comment by 2811267153** [comment]
> <img alt="image" width="631" src="https://user-images.githubusercontent.com/26263658/224598929-562833cb-42b4-4068-ab7d-50be1a58a17b.png">
> 
> 把这个去掉，简单问题自己好好排查下。

可是 我还是想请教一下， 就是 如果我现在使用nodeAPI需要怎么办？new bing只给了一段这样的代码contextBridge.exposeInMainWorld('nodeAPI', {
  send: () => ipcRenderer.send('message'),
  receive: (channel, func) => ipcRenderer.on(channel, (event, ...args) => func(...args))
})😢😢😢那我在页面里面使用window.nodeAPI.send()perload文件即使接收到以后我需要怎么添加里面的业务代码呢？

**Comment by caoxiemeihao** [comment]
是否能用 `contextBridge.exposeInMainWorld` 取决于 `contextIsolation` 值为 `true` or `false`
这么简单的问题人家 Electron 不是用 log 提示的？或者百度下也就分分钟就能知道怎么回事了不是？

> contextBridge.exposeInMainWorld('nodeAPI', {
> send: () => ipcRenderer.send('message'),
> receive: (channel, func) => ipcRenderer.on(channel, (event, ...args) => func(...args))

这段代码只是在 `contextIsolation: true` 时候的示例代码，`contextIsolation: false` 下直接用 `window.ipcRenderer = ipcRenderer` 不就行了吗？想不明白这么简单的东西么？
