### ISSUE TITLE
react-native-reanimated

### ISSUE THREAD

**Issue by AElbert** [electron-vite/electron-vite-react#127]
I configured react-native-web to be able to use react-native, now I am trying to use react-native-reanimated https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation but I can't get it to work properly. 

I got the following error:
`
file: /Users/alberto/Desktop/prod/node_modules/.pnpm/react-native-reanimated@2.14.4_react@18.2.0/node_modules/react-native-reanimated/lib/reanimated1/Transitioning.js:36:6
34:   return (props) => {
35:     return (
36:       <TransitioningContext.Consumer>
          ^
37:         {(context) => <Comp context={context} {...props} />}
38:       </TransitioningContext.Consumer>
`
Which I solved with the following configuration in `vite.config.ts`:
`
optimizeDeps: {
      esbuildOptions: {
        loader: { '.js': 'jsx' },
        resolveExtensions: [
          '.web.tsx',
          '.web.jsx',
          '.web.js',
          '.tsx',
          '.ts',
          '.js',
        ],
      },
    },
`
works correctly with `pnpm dev` but when using `pnpm build` I get the same error as above which I solved by adding babel configuration like this: 
`
build: {
      rollupOptions: {
        plugins: [
          react({
            babel: {
              presets: ['module:metro-react-native-babel-preset'],
              plugins: ['react-native-reanimated/plugin'],
            }
          }),
        ]
      }
    },
`
That solved it but now when I run the app I only see a white screen, if I add the console I see that there is this error:
`
Uncaught Error: Cannot find module './App'
Require stack: /Users/alberto/projects/Redtapp/iot-turbo/apps/iot-products/dist/index.html
`
And I don't know what to do with that anymore, I was reading that Vite 2 doesn't use optimizeDeps in prod mode that would make sense why it doesn't work in prod however I don't know if that still happens and if so how to fix it.

**Comment by AElbert** [comment]
Fix the white screen and the error:
`
Uncaught Error: Cannot find module './App' Require stack: /Users/alberto/projects/Redtapp/iot-turbo/apps/iot-products/dist/index.html
`
with 
`
build: {
      rollupOptions: {
        external: Object.keys(pkg.dependencies),
      },
    },
`
but now in production I get this error: 
`
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import TestComponent from "./test";
SyntaxError: Cannot use import statement outside a module
`


dev is still working properly but prod is the problem, it is worth mentioning that this app is inside a monorepo and the dependency that is giving this problem belongs to the monorepo.

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by AElbert** [comment]
I've been testing this temporary project https://github.com/AElbert/electron-vite-reanimated and realized that the problem is not the package in the monorepo.

**Comment by caoxiemeihao** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/226334386-ea2299aa-4b7d-4b66-a926-72ba0db92b6e.png">

Normally, Vite doesn't build `react-native-reanimated` correctly because it outputs a non-standard file.

**Comment by AElbert** [comment]
That's the problem, the solution was: 
`
optimizeDeps: { esbuildOptions: { loader: { '.js': 'jsx' }, resolveExtensions: [ '.web.tsx', '.web.jsx', '.web.js', '.tsx', '.ts', '.js', ], }, }
`
But that only works in dev, making build does not work.

**Comment by AElbert** [comment]
Maybe the problem is that you have not added the babel plugin as it says in the reanimated documentation https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/ 

I added it as follows

```
build: {
  rollupOptions: {
    plugins: [
      react({
        babel: {
          presets: ['module:metro-react-native-babel-preset'],
          plugins: ['react-native-reanimated/plugin'],
        }
      }),
    ]
  }
}
```

A new error appeared about not finding electron but I solved it by changing the version as follows `"electron": "^23.1.1" => "electron": "23.1.1"`

And the build script works, the problem is that when I run the release I get the following error in the app console:

```
Uncaught Error: Cannot find module './App'
Require stack:
- /Users/alberto/projects/Redtapp/iot-turbo/apps/iot-products/release/1.0.0/mac/iot-products.app/Contents/Resources/app.asar/dist/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:1002:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:848:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at index-90fd445b.js:1:194
```

Also try the following:
```
build: {
  rollupOptions: {
    preserveSymlinks: true,
    external: Object.keys(pkg.dependencies),
  }
}
```
But when I build and run, I get this error in the app console:
```
Uncaught /Users/alberto/Desktop/iot-products/release/2.1.0/mac/electron-vite-reanimated.app/Contents/Resources/app.asar/node_modules/react-native-reanimated/lib/index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import * as Animated from './Animated';
                                                                                                                                                           ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:100:7)
    at createScript (node:vm:265:10)
    at Object.runInThisContext (node:vm:313:10)
    at wrapSafe (node:internal/modules/cjs/loader:1083:15)
    at Module._compile (node:internal/modules/cjs/loader:1130:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
```

**Comment by caoxiemeihao** [comment]
I tried to build `react-native-web` via a plugin, but it's pretty bad, and in general Rollup doesn't handle CommonJs very well.
If I were to fix this entirely in Vite, it would probably take me a lot of time.

If this project were mine, I would choose to build `react-native-web` as a Bundle using Webpack first, which would save me a lot of time.

---

This is a half-finished product.

```ts
import { rmSync } from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { defineConfig, transformWithEsbuild } from 'vite'
import react from '@vitejs/plugin-react'
import electron from 'vite-electron-plugin'
import { customStart, loadViteEnv } from 'vite-electron-plugin/plugin'
import renderer from 'vite-plugin-electron-renderer'
import flowRemoveTypes from 'flow-remove-types'
import pkg from './package.json'

// https://vitejs.dev/config/
export default defineConfig(({ command }) => {
  rmSync('dist-electron', { recursive: true, force: true })

  const sourcemap = command === 'serve' || !!process.env.VSCODE_DEBUG

  return {
    build: {
      rollupOptions: {
        external: Object.keys(pkg.dependencies),
      },
      minify: false,
    },
    optimizeDeps: {
      esbuildOptions: {
        loader: { '.js': 'jsx' },
        resolveExtensions: [
          '.web.tsx',
          '.web.jsx',
          '.web.js',
          '.tsx',
          '.ts',
          '.js',
        ],
      },
    },
    resolve: {
      alias: {
        'react-native': 'react-native-web', // it should only be for the files in the src dir
        '@': path.join(__dirname, 'src'),
      },
      extensions: [
        '.js',
        '.ts',
        '.jsx',
        '.tsx',
        '.json',
        '.android.js', '.ios.js', // react-native/Libraries/StyleSheet/PlatformColorValueTypes
      ],
    },
    plugins: [
      {
        name: 'vite-plugin/react-native-reanimated',
        enforce: 'pre', // to intercept `alias`
        apply: 'build',
        resolveId(source, importer) {
          if (
            /\/node_modules\/react-native(-reanimated)?\//.test(importer) &&
            source.startsWith('react-native-web/')
          ) {
            // The file in `react-native-reanimated` should not be resolve by `alias`.
            source = source.replace('react-native-web', 'react-native')

            return createRequire(import.meta.url).resolve(source)
          }
        },
        async transform(code, id) {
          if (!id.endsWith('.js')) return

          code = code.replace('__DEV__', 'false')

          if (id.includes('/node_modules/react-native-reanimated/')) {
            // The js file in `react-native-reanimated` contains the JSX element.
            return transformWithEsbuild(code, id, { loader: 'jsx' })
          }

          if (/\/node_modules\/@?react-native\//.test(id)) {
            // The js file in `react-native` use the Flow, like TypeScript.
            const output = flowRemoveTypes(code, {})

            // { code: output.toString(), map: output.generateMap() }
            const result = await transformWithEsbuild(output.toString(), id, {
              loader: 'tsx', // some files don't have `@flow` comments
              sourcefile: id,
            })

            // `cjs` -> `esm`
            const match = result.code.match(/module\.exports = (\w+);/)
            if (match) {
              const [module_exports, export_default] = match
              result.code = result.code.replace(module_exports, `export { ${export_default} as default };`)
            } else {
              // node_modules/react-native/Libraries/Alert/RCTAlertManager.android.js
              const match2 = result.code.match(/module\.exports = /)
              if (match2) {
                const [module_exports2] = match2
                result.code = result.code.replace(module_exports2, 'export default ')
              }
            }

            return result
          }
        },
      },
      react(),
      electron({
        include: [
          'electron'
        ],
        transformOptions: {
          sourcemap,
        },
        plugins: [
          ...(!!process.env.VSCODE_DEBUG
            ? [
              // Will start Electron via VSCode Debug
              customStart(() => console.log(/* For `.vscode/.debug.script.mjs` */'[startup] Electron App')),
            ]
            : []),
          // Allow use `import.meta.env.VITE_SOME_KEY` in Electron-Main
          loadViteEnv(),
        ],
      }),
      // Use Node.js API in the Renderer-process
      renderer({
        nodeIntegration: true,
      }),
    ],
    server: !!process.env.VSCODE_DEBUG ? (() => {
      const url = new URL(pkg.debug.env.VITE_DEV_SERVER_URL)
      return {
        host: url.hostname,
        port: +url.port,
      }
    })() : undefined,
    clearScreen: false,
  }
})
```

**Comment by AElbert** [comment]
Actually I have found a lot of problems with reanimated, personally I recommend to look for another option while getting more support for react native web.
