### ISSUE TITLE
Problem rendering map (mapbox) in the application

### ISSUE THREAD

**Issue by vininunes** [electron-vite/electron-vite-react#128]
I used this boilerplate in my project, but I found a problem when using a map that is the core of the application.

I installed the base libraries for the map I use. 

`yarn add mapbox-gl react-map-gl`

Added map component in **App.tsx** file

```
import "./App.scss";
import Map from "react-map-gl";

function App() {
  return (
    <div className="App">
      <Map
        mapboxAccessToken="[MAP_BOX_TOKEN]"
        initialViewState={{
          longitude: -122.4,
          latitude: 37.8,
          zoom: 14,
        }}
        style={{ width: 600, height: 400 }}
        mapStyle="mapbox://styles/mapbox/streets-v9"
      />
    </div>
  );
}

export default App;
```

Problem found

![image](https://user-images.githubusercontent.com/62775378/226502996-f0768827-28a4-41b9-8533-b6cc152f00b5.png)

`Error: Map is not supported by this browser`

I use this same library in web applications.

I looked for some solutions but all without success. Maybe it's something related to WEB GL or Hardware Acceleration.

Repository with the reproduction of the environment: https://github.com/vininunes/electron-react-vite-mapbox-error

I'm going to leave this token active for a few days so that the tests can be done: 

`pk.eyJ1Ijoidm51bnhzIiwiYSI6ImNsZmhtdDN2azFsZnkzcHRheTBrcmd2eW0ifQ.2zkjYNRhOCPz2IwsPtZ6_g`

**Comment by yurui01** [comment]
That's the problem.  

<img width="901" alt="image" src="https://user-images.githubusercontent.com/23043361/226787606-d7ec0a87-83e6-46eb-b72e-87ea0e406d16.png">

**Just delete `index.html` `meta` tag**
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css"
      rel="stylesheet"
    />
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js"></script>
    <title>Electron + Vite + React</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>

```

**Comment by caoxiemeihao** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/226830669-d7154f82-d870-488a-90ca-c017022f1cd8.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/226830842-a0592f37-9507-4c2d-b6b1-ee9e637bd471.png">

Is this paid product?

**Comment by caoxiemeihao** [comment]
1. First

```diff
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css"
      rel="stylesheet"
    />
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js"></script>
-   <meta
-     http-equiv="Content-Security-Policy"
-     content="script-src 'self' 'unsafe-inline';"
-   />
    <title>Electron + Vite + React</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
```

2. Second

<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/226832808-c01652ad-42c5-4a58-857a-e824c69f6ac7.png">
