### ISSUE TITLE
how debug Renderer Process

### ISSUE THREAD

**Issue by bluelightsky** [electron-vite/electron-vite-react#129]
devTool show: DevTools failed to load source map: Could not load content for http://localhost:5173/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by bluelightsky** [comment]
vite-plugin-electron-renderer don't support set sourcemap

**Comment by RSS1102** [comment]
> vite-plugin-electron-renderer 不支持 set sourcemap
I have also encountered this problem. Generally, you can wait 1-2 minutes for the resource to load.

Or try accessing after packaging (if possible, there is no problem).

---

"I also searched Electron for a lot of questions about 'devTool show: DevTools failed to load source map:'.". But there was no satisfactory response.

**Comment by caoxiemeihao** [comment]
你猜 👻

**Comment by caoxiemeihao** [comment]
> vite-plugin-electron-renderer don't support set sourcemap

vite.config.ts

```
export default {
  build: {
    sourcemap: 'inline',
  }
}
```

**Comment by caoxiemeihao** [comment]
Pull the latest code
