### ISSUE TITLE
打包后项目启动时间较长

### ISSUE THREAD

**Issue by 2811267153** [electron-vite/electron-vite-react#133]
hello,你好, 我不知道你怎么称呼 我就先叫你楼主好吧!
首先先介绍一下我的问题, 我这边在打包electron文件之后, 正常启动这个程序,从启动到正常显示Home页面,需要特别特别久的时间,差不多需要四十多秒的时间,这不包含数据加载, 因为我给程序添加了loading状态.我知道这个可能不是您这个项目的问题 但是因为我完全不知道,这边我改怎么办,所以才会冒昧的打扰你, 请你提几个解决问题的思路, 谢谢!!!!

**Comment by 2811267153** [comment]
目前这个项目打包之后有150mb左右不知道算不算太大, preload我没有接触, IPC请求 我倒挺多,一百行的样子, 有一个用户cookie的, 两个保存历史记录的,以及返回历史记录的 还有三个是监听点击程序, 最大化, 最小化,关闭的 就没有别的了, 这是我用的库
![image](https://user-images.githubusercontent.com/67245639/228005054-31316df8-2eed-4078-8d3f-2967dea008f0.png)
以及我用来做IPC通信的
![image](https://user-images.githubusercontent.com/67245639/228005421-df62fce6-5177-4019-8b7b-ad44e2398722.png)
![image](https://user-images.githubusercontent.com/67245639/228005502-0c4cd660-868f-47a5-8af8-da2693b54b8c.png)

**Comment by caoxiemeihao** [comment]
在 main.tsx/App.tsx 中写了好多初始化的逻辑？有设计到 IO 的吗？
其次依赖包放到 `devDependenices` 中应用程序包体会小一些。

**Comment by 2811267153** [comment]
![image](https://user-images.githubusercontent.com/67245639/228227392-f3b88bf2-db08-4bc2-9cb0-25fc3cd0f975.png)
我在APP里面主要就是放的路由

**Comment by 2811267153** [comment]
在homePage里面有sange三个主进程通讯相关的useEffect别的都没有了
![image](https://user-images.githubusercontent.com/67245639/228228628-7ebc70ad-a23e-4249-b52a-aafa93b0071c.png)

**Comment by caoxiemeihao** [comment]
主进程有阻塞逻辑么，建议换个 Electron 版本试试，往前换。

**Comment by 2811267153** [comment]
主进程并没有什么异步代码, 我尝试一下换个electron版本试试




哇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "electron-vite/electron-vite-react"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 上午10:38
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [electron-vite/electron-vite-react] 打包后项目启动时间较长 (Issue #133)





 
主进程有阻塞逻辑么，建议换个 Electron 版本试试，往前换。

**Comment by 2811267153** [comment]
我今天下午的时候 尝试了一下更换electron版本 好像是到最新版本了 尝试打包了一下, 启动变得很快了, 我的问题解决了!!!!非常感谢

**Comment by caoxiemeihao** [comment]
感谢地话可以扫码捐赠的 :)

**Comment by 2811267153** [comment]
我也没多少钱, 就先给点辛苦费(●ˇ∀ˇ●)

**Comment by caoxiemeihao** [comment]
哈哈哈，感谢支持，不在多少，用爱发电 ❤️
