### ISSUE TITLE
Error: Argument of type 'null' is not assignable to parameter of type 'ProgressInfo'.

### ISSUE THREAD

**Issue by adnanlah** [electron-vite/electron-vite-react#134]
Hello,

I copy-pasted the content of the `update.ts` file and added it to my project. I get this error: `Argument of type 'null' is not assignable to parameter of type 'ProgressInfo'.` in this line of code:
```ts
autoUpdater.on('error', error => callback(error, null))
```
<img width="457" alt="image" src="https://user-images.githubusercontent.com/8447982/230988950-6bdb9134-698d-4ed6-aa20-effb8f7beee0.png">
Thanks.

**Comment by RSS1102** [comment]
Sorry, this is indeed a derivation error for my type. I have fixed it in the latest code. Thank you.
