### ISSUE TITLE
打包后报错，测试运行是好的

### ISSUE THREAD

**Issue by wingjson** [electron-vite/electron-vite-react#138]
![image](https://user-images.githubusercontent.com/20148421/232981199-28e1f59c-ca91-4979-b5a8-d4a75cb6593d.png)
这是我的packge.json
![image](https://user-images.githubusercontent.com/20148421/232981348-05ef7df6-28fa-46fa-bf8e-a623e9349fdf.png)
这是报错模块未找到。但是我本身代码里没引用这些，一个个安装后大概十个模块左右，最后安装好lre-cache后。报错
<img width="483" alt="46e46dd622f23c110f771ac4392587b" src="https://user-images.githubusercontent.com/20148421/232981651-5651b477-0e4f-4a78-856a-b06c2fa261b8.png">
报错IRU is not construct ,但是代码里没有引用这些

**Comment by 981349873** [comment]
![image](https://user-images.githubusercontent.com/20148421/232981953-49f50c5c-be91-4790-9d1e-92e026671433.png)
代码里用了这些。
![image](https://user-images.githubusercontent.com/20148421/232982061-4d91b8e5-fe3f-4546-ae0e-697952f21369.png)
这是main.js

是因为我用cnpm安装的原因吗，公司网络不好，只有cnpm能用

**Comment by RSS1102** [comment]
建议删除`node_modules`,使用`yarn`进行重新安装，或者配置`npmrc`,改用taobao源进行尝试。

**Comment by 981349873** [comment]
我试一下

**Comment by 981349873** [comment]
问题解决了，cnpm安装的有问题，但是现在又出了新的问题，打包后白屏，啥也不显示，就是这样，配置啥的就是上面我发的，=没动![image](https://user-images.githubusercontent.com/20148421/233004759-5a674c5c-5510-496b-a2fe-08bcd53cd348.png)

**Comment by 981349873** [comment]
问题解决了，cnpm安装的有问题，但是现在又出了新的问题，打包后白屏，啥也不显示，就是这样，配置啥的就是上面我发的，
![image](https://user-images.githubusercontent.com/20148421/233005515-0a3a5287-683c-4cbf-9db9-4818ac0ef0d0.png)
，好难😂

**Comment by RSS1102** [comment]
> 问题解决了，cnpm安装的有问题，但是现在又出现了新的问题，打包后白屏，啥也不显示，就是这样，配置啥的就是上面我发的，， 好难 ![图像](https://user-images.githubusercontent.com/20148421/233005515-0a3a5287-683c-4cbf-9db9-4818ac0ef0d0.png)😂

dev模式下是有显示的吗？

你这个是下载的这个模板之后就打包的吗？

**Comment by RSS1102** [comment]
建议你 在另一个文件夹内克隆当前模板，然后进行打包查看效果。

如可
1，将代码分批移植过来，测试在哪个部分打包没有成功。
2，或者你再次重新安装依赖，是否安装依赖不全。
3，或者你上传最小demo，以供测试排错。

**Comment by 981349873** [comment]
找到问题了，是packge.json里加build :extraresources 这个配置项后打包就会白屏。但是我想在程序里引用外部exe.把外部exe一起打包进去该怎么配置呢

**Comment by RSS1102** [comment]
> "build": { "extraResources": [ { "from": "extraResources", "to": "resources" } ] }, 就是这个配置，加了后打包能把外部exe打包进去，但是白屏

试试这个
```json5
  "win": {
     extraFiles: [
      { from: "libs/code/bin/Release", to: ".", filter: ["*.exe"] },
    ],
```
将`libs/code/bin/Release`下的所有以`.exe`结尾的文件打包到根目录`.`下

**Comment by 981349873** [comment]
我这样试了还是不行😂，没打包进去，现在我就先手工拖进unpack文件夹里，在用inno setup重新打包了

**Comment by 981349873** [comment]
您那边试的话可以吗，我这边别的配置基本没动过

**Comment by RSS1102** [comment]
> 您那边试的话可以吗，我这边别的配置基本没动过

我这边是可以的。

**Comment by RSS1102** [comment]
> 我这样试了还是不行😂，没打包进去，现在我就先手工拖进unpack文件夹里，在用inno setup重新打包了

或者你尝试放在(public)[https://vitejs.dev/guide/assets.html#the-public-directory]下，尝试能否可以。

**Comment by Achilles822** [comment]
遇到相同的问题了，楼主能给一个使用regedit这个库的demo吗，打包后就白屏了，折腾了好久还是不行

**Comment by RSS1102** [comment]
> 遇到相同的问题了，楼主能给一个使用regedit这个库的demo吗，打包后就白屏了，折腾了好久还是不行

你是已经在electron集成了regedit了吗？（在dev下正常吗）
建议你新开个issue讨论一下。

**Comment by Achilles822** [comment]
> 

看起来是同个问题，就不另开了

**Comment by Achilles822** [comment]
> > 遇到相同的问题了，楼主能给一个使用regedit这个库的demo吗，打包后就白屏了，折腾了好久还是不行
> 
> 你是已经在electron集成了regedit了吗？（在dev下正常吗） 建议你新开个issue讨论一下。

看起来是同个问题，就不另开了，dev下一切正常的。build后就不行，这个问题应该本地很好复现的，随便读个注册表打包就好了

**Comment by RSS1102** [comment]
> > > 遇到相同的问题了，楼主能给一个使用regedit这个库的demo吗，打包后就白屏了，折腾了好久还是不行
> > 
> > 
> > 你是已经在electron集成了regedit了吗？（在dev下正常吗） 建议你新开个issue讨论一下。
> 
> 看起来是同个问题，就不另开了，dev下一切正常的。build后就不行，这个问题应该本地很好复现的，随便读个注册表打包就好了

查看打包后的根目录是否已经把`.cpp`文件打包进去。
在生产环境下打开devtools查看报错问题

**Comment by 981349873** [comment]
我的也还是没打包进去，我就暂时直接复制进去了😂，加build参数白屏，devtools里显示是加载html失败。不知道是不是地址不对

**Comment by 981349873** [comment]
明天我弄个最小demo上传上来，您帮忙看下吧😂

**Comment by NeverlandForKi** [comment]
> 

遇到同样问题了，dev正常 build之后白屏，打开控制台也没有报错，看html内容是没有渲染，请问你那边解决了吗？

**Comment by RSS1102** [comment]
> > 
> 
> 遇到同样问题了，dev正常 build之后白屏，打开控制台也没有报错，看html内容是没有渲染，请问你那边解决了吗？

你多等待1-2分钟，如果还不行，重新保存一下electron文件reload一下试试？

**Comment by NeverlandForKi** [comment]
> > > 
> > 
> > 
> > 遇到同样问题了，dev正常 build之后白屏，打开控制台也没有报错，看html内容是没有渲染，请问你那边解决了吗？
> 
> 你多等待1-2分钟，如果还不行，重新保存一下electron/下的文件reload一下试试？

感谢回复，我就2个页面都是展示的，没有涉及到和接口交互的请求，多等待了好一会儿也没有反应，css倒是正常引入了，只是页面和dev对比 没有引入js。 您说的重新保存一下electron下的文件reload是啥意思？ 没明白。。

**Comment by RSS1102** [comment]
> > > > 
> > > 
> > > 
> > > 遇到同样问题了，dev正常 build之后白屏，打开控制台也没有报错，看html内容是没有渲染，请问你那边解决了吗？
> > 
> > 
> > 你多等待1-2分钟，如果还不行，重新保存一下electron/下的文件reload一下试试？
> 
> 感谢回复，我就2个页面都是展示的，没有涉及到和接口交互的请求，多等待了好一会儿也没有反应，css倒是正常引入了，只是页面和dev对比 没有引入js。 您说的重新保存一下electron下的文件reload是啥意思？ 没明白。。

我以为你是在dev模式下，如果是在build下，你先尝试下载模板build之后看是否能正常显示，然后再排查自己的代码。

**Comment by NeverlandForKi** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 遇到同样问题了，dev正常 build之后白屏，打开控制台也没有报错，看html内容是没有渲染，请问你那边解决了吗？
> > > 
> > > 
> > > 你多等待1-2分钟，如果还不行，重新保存一下electron/下的文件reload一下试试？
> > 
> > 
> > 感谢回复，我就2个页面都是展示的，没有涉及到和接口交互的请求，多等待了好一会儿也没有反应，css倒是正常引入了，只是页面和dev对比 没有引入js。 您说的重新保存一下electron下的文件reload是啥意思？ 没明白。。
> 
> 我以为你是在dev模式下，如果是在build下，你先尝试下载模板build之后看是否能正常显示，然后再排查自己的代码。

下载模版build之后是正常的，排查了一下，应该是因为我引入了`react-router-dom`，main.tsx的代码是这样的：
`
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";
import "./samples/node-api";
import "./index.scss";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);

postMessage({ payload: "removeLoading" }, "*");

`

**Comment by NeverlandForKi** [comment]
貌似用BrowserRouter包裹住App之后，build之后是没有渲染App组件的，上面引入的node-api和index.scss文件在控制台是可以看到正常引入的

**Comment by NeverlandForKi** [comment]
> 

意思是不能用react-router吗？ 只能用`electron.toWindow`这种方式去跳转新页面吗？ 这样可以理解就是一个多页应用了，对状态管理不是很友好啊。。

**Comment by NeverlandForKi** [comment]
> 貌似用BrowserRouter包裹住App之后，build之后是没有渲染App组件的，上面引入的node-api和index.scss文件在控制台是可以看到正常引入的

这个问题感觉应该是一个bug啊，dev是正常的，大佬可否查一下修复一下
