### ISSUE TITLE
怎么打包静态资源文件

### ISSUE THREAD

**Issue by 2811267153** [electron-vite/electron-vite-react#140]
大佬大佬 请问怎么配置打包的静态资源文件位置呀
![image](https://user-images.githubusercontent.com/67245639/233817929-d3ee58fa-90f8-43e0-a060-2954f0dd7e0c.png)
我这样些好像不对,他好像还是找不到位置能不能请教一下

**Comment by RSS1102** [comment]
1.放在根目录下`public`
2.Windows下尝试
```
 "win": {
     extraFiles: [
      { from: "libs/code/bin/Release", to: ".", filter: ["*.exe"] },
    ],
```
见[#extrafiles](https://www.electron.build/configuration/contents.html#extrafiles)

---

或者你尝试被files包含.
见[#files](https://www.electron.build/configuration/contents.html#files)

**Comment by 2811267153** [comment]
> { from: "libs/code/bin/Release", to: ".", filter: ["*.exe"] },
哦哦 非常感谢 谢谢大佬😊😊😊
