### ISSUE TITLE
Build gives blank page with react-router

### ISSUE THREAD

**Issue by SwapnilSoni1999** [electron-vite/electron-vite-react#142]
While running the app in dev script the application is working fine with react-router
However whenver the build is made either linux or windows both of them gives blank white page 

Incase if the folder structure is something an issue then I currently have different folders other than components/ 
(such as layouts/, outlets/, interfaces/ etc)

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by one-god** [comment]
我也是出现这个问题，开完了，打完包发现 页面空白，找不到路由

**Comment by SwapnilSoni1999** [comment]
> 我也是出现这个问题，开发完了，打完包发现 页面空白，找不到路由

只需使用“哈希路由器”就可以工作。
