### ISSUE TITLE
electron托盘在线上版本不生效

### ISSUE THREAD

**Issue by 2811267153** [electron-vite/electron-vite-react#145]
![image](https://github.com/electron-vite/electron-vite-react/assets/67245639/2480f36e-add6-46c7-9300-c9bbb127a929)
这段代码 在开发环境下运行是 可以正常显示出托盘以及对应的菜单栏,但是在打包以后就不生效了, 找了好多攻略好像没有这方面的问题特地请教一下
![image](https://github.com/electron-vite/electron-vite-react/assets/67245639/ccc1e15c-1eb5-4e95-87f9-4c53c94e7170)
这张图是线上版本的托盘 
![image](https://github.com/electron-vite/electron-vite-react/assets/67245639/88e4e3bd-58ad-40a2-af3c-9bbf9493c88f)
这个是开发环境的托盘还有个小问题就是 开发环境下的托盘显示的图标好像是electron默认的图标, 但是 我给他修改成了我的图片也没有显示出了, 您知道原因吗

**Comment by caoxiemeihao** [comment]
咦~你在写音乐 APP 我刚好这两天也在写 😂
https://github.com/caoxiemeihao/music-desktop-application

**Comment by 2811267153** [comment]
哈哈🤣🤣

**Comment by 2811267153** [comment]
这个我当时 入门花了我好久的时间😂

**Comment by caoxiemeihao** [comment]
emmm...
确实很费时间，我这两天也很折腾了，主要怕音源很废人。。。
Electron 的 API 还好，大概的碰到的问题 Google 一下差不多就有答案了 😆
