### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by niu-grandpa** [electron-vite/electron-vite-react#146]
when i clone this project and install， but there are some error，Please use @electron/asar moving forward. There is no API change, just a package name change

**Comment by RSS1102** [comment]
> when i clone this project and install， but there are some error，Please use @electron/asar moving forward. There is no API change, just a package name change

Attempt to switch download sources

**Comment by niu-grandpa** [comment]
切换了镜像源，但依然出错
![image](https://github.com/electron-vite/electron-vite-react/assets/62378518/af26869f-0e46-411c-8334-588fecb35810)

**Comment by caoxiemeihao** [comment]
不要用中文路径！

**Comment by niu-grandpa** [comment]
ok, thanks! this problem should add this line of code 👉 electron_mirror="https://npm.taobao.org/mirrors/electron/" 👈in the .npmrc file
