### ISSUE TITLE
Cancel BLE device request

### ISSUE THREAD

**Issue by AElbert** [electron-vite/electron-vite-react#148]
Elctron released a version to be able to cancel `navigator.bluetooth.requestDevice` as specified in https://github.com/electron/electron/pull/37601.

According to the new documentation about this available at https://www.electronjs.org/docs/latest/tutorial/devices#web-bluetooth-api. The problem is that when I use `window.electronAPI.cancelBluetoothRequest()` I get 

```
Unable to load preload script: /dist-electron/preload/index.js
```
```
Error: contextBridge API can only be used when contextIsolation is enabled
```

and if I try to use the function I get
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'cancelBluetoothRequest')
```

I have already updated the electron version to the newest one, but I would like to know if it is necessary to add any additional configuration for this to work properly.

**Comment by RSS1102** [comment]
sorry, i can"t find `cancelBluetoothRequest` API in [devices#web-bluetooth-api](https://www.electronjs.org/docs/latest/tutorial/devices#web-bluetooth-api).

>and for `Error: contextBridge API can only be used when contextIsolation is enabled`:
In most cases, only the main frame can send IPC messages. However, if the nodeIntegrationInSubFrames option is enabled, it is possible for child frames to send IPC messages also.

**Comment by AElbert** [comment]
An apology, the code is distributed in files in the documentation, maybe it is clearer in the git repo https://github.com/electron/electron/tree/v24.3.0/docs/fiddles/features/web-bluetooth there are the files with the necessary configurations.

**Comment by RSS1102** [comment]
> 
I hope this docs can help you：https://www.electronjs.org/docs/latest/tutorial/devices#web-bluetooth-api
