### ISSUE TITLE
after build I see white screen

### ISSUE THREAD

**Issue by ImSidow** [electron-vite/electron-vite-react#150]
if I run build I see white screen even I don't see my consoles I think react is not loading

**Comment by RSS1102** [comment]
Perhaps you should wait, it may be a cache error.

Are you trying to rebuild and wait for 1-2 minutes?

**Comment by ImSidow** [comment]
Do I need to mention out put dir in package electron build property

**Comment by RSS1102** [comment]
Did you encounter problems during the first build? Can you give me the smallest repo? To facilitate my search for issues.

**Comment by ImSidow** [comment]
Yes it my first build

this is small sample repo: https://github.com/ImSidow/small-desktop-app

**Comment by RSS1102** [comment]
> Yes it my first build
> 
> this is small sample repo: https://github.com/ImSidow/small-desktop-app

thanks.After I run it, it's normal. Is it because of network issues that `NPM` did not succeed? Try `Yarn`?
![image](https://github.com/electron-vite/electron-vite-react/assets/81673017/767bf0de-119a-4b69-961c-0c58b716bea6)

**Comment by ImSidow** [comment]
yes it works in dev for me but I want for build I mean production like (.exe, dmg,...)

**Comment by RSS1102** [comment]
https://github.com/ImSidow/small-desktop-app/blob/master/package.json#L32-L44 .An error has occurred here, you have repeated the declaration.
You should configure your program information here: https://github.com/electron-vite/electron-vite-react/blob/main/electron-builder.json5
You can see more here: https://electron-vite.github.io/build/electron-builder.html#main-config

**Comment by NeverlandForKi** [comment]
> yes it works in dev for me but I want for build I mean production like (.exe, dmg,...)

same here. did you issue this issue?

**Comment by RSS1102** [comment]
> > yes it works in dev for me but I want for build I mean production like (.exe, dmg,...)
> 
> same here. did you issue this issue?

Are you directly using templates for building?

**Comment by NeverlandForKi** [comment]
> 

感谢大佬的回复，正在试，想问一下我在mac下run build之后只有mac安装包，怎么才能打出windows的exe的安装包呢？

**Comment by RSS1102** [comment]
> > 
> 
> 感谢大佬的回复，正在试，想问一下我在mac下run build之后只有mac安装包，怎么才能打出windows的exe的安装包呢？

try it:https://electron-vite.github.io/build/electron-builder.html#build-scripts
