### ISSUE TITLE
App Icon not shown in AppImage build

### ISSUE THREAD

**Issue by ptourlas** [electron-vite/electron-vite-react#151]
Greetings!

I cloned and ran this template and I'm already using a heavily modified version of it for a project. However in both the modified version of the template and this, when running in dev mode or building an AppImage, the app icon is not showing in the left sidebar (see attached images).

Any suggestion on how to fix or some starting points to study?

OS: Ubuntu 20.04
npm ver. : 8.1.0
node ver. : 16.13.0

![Screenshot from 2023-06-14 18-13-10](https://github.com/electron-vite/electron-vite-react/assets/46487703/c3571cc5-f9af-4d8c-a961-c7a0ff3fad3c)
![Screenshot from 2023-06-14 18-17-11](https://github.com/electron-vite/electron-vite-react/assets/46487703/154d0e60-cd90-4457-ad45-5599530058e9)

**Comment by caoxiemeihao** [comment]
When you don't set any icon files, does it show the default Electron icon? If so, then the problem shoud come from Electron itself.

**Comment by ptourlas** [comment]
Unfortunately, no. The problem persists if I change all icon or delete them entirely.

**Comment by RSS1102** [comment]
> 很不幸的是，不行。如果我更改所有图标或完全删除它们，问题仍然存在。
Did you also experience this situation during the initial template?

**Comment by ptourlas** [comment]
Cloning and starting template "as is", fails as well.

**Comment by RitchieP** [comment]
I would assume you did this, but to clarify, did you set the icons in the electron main file?

**Comment by ptourlas** [comment]
@RitchieP  I am not sure if I discarded that in my own version of the codebase (may have botched it and not notice :sweat_smile: ) but cloning the template from GitHub as is, does not work either. Isn't anyone else able to reproduce this?
