### ISSUE TITLE
主进程如何不都生成一个js文件啊。

### ISSUE THREAD

**Issue by lanayalouisforever** [electron-vite/electron-vite-react#153]
您好，我用这个项目的代码，正常运行后。
主进程 main/index.ts
`import { update } from './update'`
改成如下
`const { update } =require('./update')`

npm run dev，会提示无法找到./update

使用import xx from xx 形式，没有这个错误。但是会影响启动速度吧。

然后最后主进程就只有main.js和preload.js，main.js会越来越大

**Comment by caoxiemeihao** [comment]
1. `vite-plugin-electron` 本身支持多入口构建
<img width="512" alt="image" src="https://github.com/electron-vite/electron-vite-react/assets/26263658/73d49aa7-c080-4c9e-8282-ec44aaa1fdad">

2. `entry` 选项支持多入口构建
<img width="573" alt="image" src="https://github.com/electron-vite/electron-vite-react/assets/26263658/5dd455ff-3aa6-4bfa-8a74-57a4e9cba147">

3. 使用 `build.rollupOptions.input` 多入口构建
