### ISSUE TITLE
electron 导出 session 报错

### ISSUE THREAD

**Issue by JarvisMarkDown** [electron-vite/electron-vite-react#154]
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/electron.js?v=220f7369' does not provide an export named 'session'

**Comment by caoxiemeihao** [comment]
<img width="771" alt="image" src="https://github.com/electron-vite/electron-vite-react/assets/26263658/115585ee-db51-4640-b038-cbfe889b63f3">

https://www.electronjs.org/docs/latest/api/session
