### ISSUE TITLE
Why I can't use firebase

### ISSUE THREAD

**Issue by onemanking** [electron-vite/electron-vite-react#157]
I try to add these get data from Firebase realtime db in `electron/main.ts` and never get the data from it
`electron/main.ts`
```
// Test active push message to Renderer-process.
  win.webContents.on("did-finish-load", async () => {
    const snapshot = await firebase.database().ref("version").get(); // **it not work**
    const version = snapshot.val() as string; // **never reach to this point**
    console.log(`Version: ${version}`);
  });
```

but if I use it in the render process, it will work
`App.tsx`
```
function App() {
  const firebaseApp = firebase.initializeApp(firebaseConfig);
  const db = firebaseApp.database();
  const versionRef = db.ref("version");
  const [version, setVersion] = useState("0.0.0");

  useEffect(() => {
    versionRef.get().then((snapshot) => setVersion(snapshot.val() as string)); // **it's work!**
  });

  return (
    <div className="App">
      <h1>Version: {version}</h1>
    </div>
  )
}
```

Do I need to set up or config something? Thank you

**Comment by caoxiemeihao** [comment]
I not sure what you wath.
The following line not log output in your App?

```diff
// Test active push message to Renderer-process.
  win.webContents.on("did-finish-load", async () => {
    const snapshot = await firebase.database().ref("version").get(); // **it not work**
    const version = snapshot.val() as string; // **never reach to this point**
+   console.log(`Version: ${version}`);
  });
```

**Comment by onemanking** [comment]
> 

yes, nothing happens after await to get the data.
and if I create a project in another way. like using `npm init electron-app@latest my-new-app -- --template=webpack-typescript` the firebase code in `main.ts` will work.

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by onemanking** [comment]
> Can you provide a minimal reproduction repo?

https://github.com/onemanking/electron-vite-firebase

here you go

**Comment by caoxiemeihao** [comment]
<img width="700" alt="image" src="https://github.com/electron-vite/electron-vite-react/assets/26263658/763d22ff-5e65-4ad7-bc0f-f8c1d2e47bfa">

Works on my local machine

**Comment by onemanking** [comment]
> <img alt="image" width="700" src="https://user-images.githubusercontent.com/26263658/258044978-763d22ff-5e65-4ad7-bc0f-f8c1d2e47bfa.png">
> Works on my local machine

it only log for firebase object. You should try to access to database or another function and see if it works

**Comment by caoxiemeihao** [comment]
This requires using a firebase account, I do not have a firebase account available.

**Comment by MeBadDev** [comment]
> > <img alt="image" width="700" src="https://user-images.githubusercontent.com/26263658/258044978-763d22ff-5e65-4ad7-bc0f-f8c1d2e47bfa.png">
> > Works on my local machine
> 
> it only log for firebase object. You should try to access to database or another function and see if it works

Works on my machine too
