### ISSUE TITLE
contextBridge communication via preload is not working

### ISSUE THREAD

**Issue by umerjaved178** [electron-vite/electron-vite-react#160]
Unable to get window.electronAPI on the page

> const { contextBridge, ipcRenderer } = require("electron");
> contextBridge.exposeInMainWorld("electronAPI", {
>     setTitle: (title) => ipcRenderer.send("send-message", title),
> });

node integration is on

**Comment by umerjaved178** [comment]
@caoxiemeihao the core functionality of electronjs is broken, can you please look into this issue

**Comment by caoxiemeihao** [comment]
```diff
  win = new BrowserWindow({
    title: 'Main window',
    icon: join(process.env.VITE_PUBLIC, 'favicon.ico'),
    webPreferences: {
      preload,
      // Warning: Enable nodeIntegration and disable contextIsolation is not secure in production
      // Consider using contextBridge.exposeInMainWorld
      // Read more on https://www.electronjs.org/docs/latest/tutorial/context-isolation
-     nodeIntegration: true,
-     contextIsolation: false,
    },
  })
```

If this doesn't solve your problem, you can use the project created by `create electron-vite`, that is different.

**Comment by amirrezapanahi** [comment]
isn't the electorn-vite project with react the same as this one (electron-vite-react)? so you end up with the same scaffold? I am also having this issue

**Comment by yejimeiming** [comment]
<img width="696" alt="image" src="https://github.com/user-attachments/assets/f472d0e0-5cd8-43d1-8b4d-e6aaa6c8520c">

---

`contextBridge.exposeInMainWorld('ipcRenderer', {...})` registered in `electron/preload/index.ts` means it can be used directly in the **renderer process**.

For example:

```js
// src/demos/ipc.ts

window.ipcRenderer.on('xxxx', (_event, ...args) => {})

window.ipcRenderer.send('xxxx', ...args)

const result = await window.ipcRenderer.invoke('xxxx', ...args)
```

**Comment by sow-coding** [comment]
Thank you @yejimeiming, actually it is obvious, I might be a bit silly sometimes lol
