### ISSUE TITLE
Wrong Template (I guess...)

### ISSUE THREAD

**Issue by aktselite** [electron-vite/electron-vite-react#162]
I tried running `npm create electron-vite@latest` its says download package electron-vite@0.3.0 and i continued but its not generating the template with sass and no e2e, just simple src folder and electron folder with css and tsx files... 

Please help me i want tha sass one

**Comment by caoxiemeihao** [comment]
Oh!

```sh
git clone https://github.com/electron-vite/electron-vite-react.git
```

The project created by `npm create electron-vite@latest` and `electron-vite-react` are different.
