### ISSUE TITLE
process.env.APPDATA is undefined

### ISSUE THREAD

**Issue by Hybueno09** [electron-vite/electron-vite-react#163]
我想在 Renderer Process 中获取process.env.APPDATA，开发环境中能正常获取到，打包后就是 undefined 了，请问是哪里要额外配置吗

**Comment by caoxiemeihao** [comment]
`process.env.XXX` 配置用 `define` 👉 https://vitejs.dev/config/shared-options.html#define
`import.meta.env.XXX` 是 Vite 更推荐的方式 👉 https://vitejs.dev/guide/env-and-mode.html#env-variables
