### ISSUE TITLE
How to add SQLITE to the project

### ISSUE THREAD

**Issue by junjielyu13** [electron-vite/electron-vite-react#165]
As the title, how to add [sqlite3](https://github.com/TryGhost/node-sqlite3) to the project, I can't add and start normally.

**Comment by caoxiemeihao** [comment]
1. Use in Main process(**recommend**)
https://github.com/Jenny-pyl/music-desktop-application/blob/main/electron/main/sql.ts

3. Use in Renderer process.
https://github.com/electron-vite/vite-plugin-electron-renderer/blob/v0.14.5/examples/quick-start/renderer/samples/node.js-native-package.ts
