### ISSUE TITLE
When use pnpm and monorepo like turborepo the build app (from release) when open show an error

### ISSUE THREAD

**Issue by MiniSuperDev** [electron-vite/electron-vite-react#170]
The same as this
https://github.com/saltyshiomix/nextron/issues/278
https://github.com/pnpm/pnpm/issues/3415#issuecomment-1042428327

To solve it, in the root of the monorepo create a file `.npmrc` if not exists
and add this
```
shamefully-hoist=true
```

**Comment by RSS1102** [comment]
Please provide the minimum demo

**Comment by MiniSuperDev** [comment]
To solve it, in the root of the monorepo create a file `.npmrc` if not exists
and add this
```
shamefully-hoist=true
```
