### ISSUE TITLE
how can I change the project structure?

### ISSUE THREAD

**Issue by MiniSuperDev** [electron-vite/electron-vite-react#173]
Instead of the current:

```
├──electron/
│  ├──main
│  ├──preload
├──src/
│   └──main.tsx
```
I want something like this:

```
├──src/
│  ├──main
│  ├──preload
│  └──renderer
│  │  └──main.tsx
```

Thanks

**Comment by RSS1102** [comment]
see: https://github.com/electron-vite/electron-vite-react/blob/main/vite.config.ts#L28

**Comment by MiniSuperDev** [comment]
@RSS1102 Thanks, what about this:
https://github.com/electron-vite/electron-vite-react/blob/aea7cc5b3195e40ff209846b745715c01d1cdaf8/electron/main/index.ts#L6-L21

**Comment by RSS1102** [comment]
Here is the configuration for loading the Electron and HTML files

---
File build function:
--dist: see [vite#build-options](https://vitejs.dev/config/build-options.html#build-options).
--dist-electron: see https://github.com/electron-vite/electron-vite-react/blob/main/vite.config.ts#L28

**Comment by MiniSuperDev** [comment]
@RSS1102 Thanks, I think I got it, these are the changes I made

https://github.com/MiniSuperDev/electron-vite-react-custom-project-structure/commit/3925943c873172bcadff1a468af65cdc6ce95448
And this:
https://github.com/MiniSuperDev/electron-vite-react-custom-project-structure/blob/3925943c873172bcadff1a468af65cdc6ce95448/index.html#L15

Could you tell me if I'm missing something, it seems to work please

Thanks

**Comment by RSS1102** [comment]
This only generates `/dist ` for HTML when you build in dev mode

**Comment by MiniSuperDev** [comment]
@RSS1102 and this is fine? or should I keep the default config?

**Comment by RSS1102** [comment]
> @RSS1102 and this is fine? or should I keep the default config?这很好吗？还是我应该保留默认配置？

No, you haven't processed the path for HTML packaging, it will cause errors

**Comment by MiniSuperDev** [comment]
@RSS1102 mmm, I appreciate if you tell me how to fix it.

Thanks.

**Comment by MiniSuperDev** [comment]
@RSS1102 Thanks, I think I got it.
After move all the files to the new folder structure.

I only need to change this 3 lines:

https://github.com/MiniSuperDev/electron-vite-react-custom-project-structure/commit/aef53400f9de9bc5e41702182aedc5058990d951

I would like you to confirm if this is correct, or if I may still have an error.

Thank you so much

**Comment by RSS1102** [comment]
If he is still functioning normally after the build, it is very good. Wait until there are problems and open a new issue
