### ISSUE TITLE
[dev] `tailwindcss --watch && vite` will block running on Windows

### ISSUE THREAD

**Issue by AlexV525** [electron-vite/electron-vite-react#178]
On Windows, running such a command will be blocked since `tailwindcss --watch` will never stop so `vite` will never run.

**Comment by Xonturis** [comment]
I ran into the same problem a couple minutes ago. I found a fix, but I am not sure it is not introducing bugs. Anyway here it is: replace the dev command with `start /b tailwindcss --watch & start /b vite`. If someone have something better, please share it, I am really not sure this is a viable solution. It works with a freshly installed repo.
