### ISSUE TITLE
编译better-sqlite3不成功

### ISSUE THREAD

**Issue by l1985q** [electron-vite/electron-vite-react#184]
我使用这个框架作为起点，使用了typeorm+better-sqlite3在Main进程中使用，安装 better-sqlite3时按electron官方的文档，使用electron-rebuild进行编译，在调试阶段都能正常使用。但使用npm run build进行打包时，会使用electron-builder进行重新编译，重新编译后的better-sqlite3就不能正常使用了，编译过程中又没有任何提示、出错的信息。再重新运行npm run dev也不能操作数据库了。必须要卸载better-sqlite3再重新安装、用electron-rebuild重新编译一次才能使用。
我尝试了在package.json中配置 
"build": {
    "npmRebuild": false
  },
  打包出来的程序也不能操作数据库。这个问题如何解决呢？

**Comment by RSS1102** [comment]
你可以看看这个？https://electron-vite.github.io/guide/cpp-addons.html#example
您最好提供一个最小复现，我好能尝试分析问题，谢谢。

**Comment by l1985q** [comment]
我看过这个，但现在这个框架里已把所有的dependencies都包含到了external中，
 rollupOptions: {
    external: Object.keys('dependencies' in pkg ? pkg.dependencies : {}),
  },
我创建了一个最小实现，地址是：https://github.com/l1985q/vite-sqlite3-test.git
我的环境是windows10,vs 2022的C++编译工具包、python3.11
初次安装完better-sqlite3,按官方的文档使用electron-rebuild重新编译，执行npm run dev能正常操作数据库。
使用npm  run build打包时electron-builder会重新进行编译操作，打包出来的程序执行闪退，better-sqlite3没有正常工作。
这时再重新执行npm run dev 也是一样的闪退，再执行一次electron-rebuild依然不能修复。只有重新npm uninstall better-sqlite3再安装、编译才能正常run dev。

**Comment by caoxiemeihao** [comment]
你看看这两个 Demo
https://github.com/caoxiemeihao/electron-vite-samples/tree/main/better-sqlite3-main-process
https://github.com/caoxiemeihao/electron-vite-samples/tree/main/better-sqlite3-renderer-process
