### ISSUE TITLE
当 contextIsolation: true,  nodeIntegration: false 时，控制台报错

### ISSUE THREAD

**Issue by dealdot** [electron-vite/electron-vite-react#186]
webPreferences: {
      preload,
      // Warning: Enable nodeIntegration and disable contextIsolation is not secure in production
      // Consider using contextBridge.exposeInMainWorld
      // Read more on https://www.electronjs.org/docs/latest/tutorial/context-isolation
      nodeIntegration: false, //生产环境时要设置为 false
      contextIsolation: true, //生产环境时设置为 true
    }, 
这样设置之后 参考 以下四步设置
https://github.com/electron-vite/electron-vite-react/issues/50

但设置之后控制台报错 ，是想实现主进程和渲染进程间通过 preload.js 进行通信的功能，确定只在 main/index.ts中使用了__dirname函数

Uncaught ReferenceError: __dirname is not defined
    at node_modules/electron/index.js (index.js:4:28)
    at __require (chunk-76J2PTFD.js?v=d6d3dfc3:3:50)
    at index.js:21:34

是直接 git clone https://github.com/electron-vite/electron-vite-react.git 运行的

**Comment by caoxiemeihao** [comment]
看下这个样板代码
https://github.com/caoxiemeihao/electron-vite-samples/tree/main/quick-start
