### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Denhope** [electron-vite/electron-vite-react#198]
Hello, 
I'm trying to build project, but after building project  Error in Chrome console 

    Uncaught ReferenceError: require is not defined
    at index--orcZJ7K.js:1342:30636
    
 And  some errors about building files

    • electron-builder  version=24.9.1 os=10.0.19045
     • loaded configuration  file=D:\dev\bamos\electron-vite-react\electron-builder.json5
    • writing effective config  file=release\2.2.0\builder-effective-config.yaml
    • packaging       platform=win32 arch=x64 electron=28.2.0 appOutDir=release\2.2.0\win-unpacked
    • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign- 
    2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
    • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign- 
    2.6.0/winCodeSign-2.6.0.7z duration=1.839s
    ⨯ cannot execute  cause=exit status 2
                    out=
     7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

     Scanning the drive for archives:
     1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\kovalchukd\AppData\Local\electron-builder\Cache\winCodeSign\396443799.7z
    --
    Path = C:\Users\kovalchukd\AppData\Local\electron-builder\Cache\winCodeSign\396443799.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : ������ �� �������� �ॡ㥬묨 �ࠢ���. : 
    C:\Users\kovalchukd\AppData\Local\electron-builder\Cache\wi
    nCodeSign\396443799\darwin\10.12\lib\libcrypto.dylib
    ERROR: Cannot create symbolic link : ������ �� �������� �ॡ㥬묨 �ࠢ���. : 
    C:\Users\kovalchukd\AppData\Local\electron-builder\Cache\winCodeSign\396443799\darwi
    n\10.12\lib\libssl.dylib

                    command='D:\dev\bamos\electron-vite-react\node_modules\7zip-bin\win\x64\7za.exe' x -bd 
     'C:\Users\kovalchukd\AppData\Local\electron-builder\Cache\winCodeSign\396443799.7z' '- 
    oC:\Users\kovalchukd\AppData\Local\electron-builder\Cache\winCodeSign\396443799'
                    workingDir=C:\Users\kovalchukd\AppData\Local\electron-builder\Cache\winCodeSign
     • Above command failed, retrying 3 more times
     • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign- 
     2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
     • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign- 
     2.6.0/winCodeSign-2.6.0.7z duration=1.534s
 When I build project in Dev all it's fine.
How can I fix this bugs?

My vite.config:
   ```javascript
import { rmSync } from "node:fs";
import path from "node:path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import electron from "vite-plugin-electron/simple";
import pkg from "./package.json";
import { nodePolyfills } from "vite-plugin-node-polyfills";
import renderer from "vite-plugin-electron-renderer";
import requireTransform from "vite-plugin-require-transform";

// https://vitejs.dev/config/
export default defineConfig(({ command }) => {
  rmSync("dist-electron", { recursive: true, force: true });

  const isServe = command === "serve";
  const isBuild = command === "build";
  const sourcemap = isServe || !!process.env.VSCODE_DEBUG;

  return {
    resolve: {
      alias: {
        "@": path.join(__dirname, "src"),
      },
    },
    plugins: [
      react(),
      nodePolyfills(),
      electron({
        main: {
          // Shortcut of `build.lib.entry`
          entry: "electron/main/index.ts",
          onstart(args) {
            if (process.env.VSCODE_DEBUG) {
              console.log(
                /* For `.vscode/.debug.script.mjs` */ "[startup] Electron App"
              );
            } else {
              args.startup();
            }
          },
          vite: {
            build: {
              sourcemap,
              minify: isBuild,
              outDir: "dist-electron/main",
              rollupOptions: {
                external: Object.keys(
                  "dependencies" in pkg ? pkg.dependencies : {}
                ),
              },
            },
          },
        },
        preload: {
          // Shortcut of `build.rollupOptions.input`.
          // Preload scripts may contain Web assets, so use the `build.rollupOptions.input` instead `build.lib.entry`.
          input: "electron/preload/index.ts",
          vite: {
            build: {
              sourcemap: sourcemap ? "inline" : undefined, // #332
              minify: isBuild,
              outDir: "dist-electron/preload",
              rollupOptions: {
                external: Object.keys(
                  "dependencies" in pkg ? pkg.dependencies : {}
                ),
              },
            },
          },
        },
        // Ployfill the Electron and Node.js API for Renderer process.
        // If you want use Node.js in Renderer process, the `nodeIntegration` needs to be enabled in the Main process.
        // See 👉 https://github.com/electron-vite/vite-plugin-electron-renderer
        renderer: {},
      }),
      renderer(),
      requireTransform({}),
    ],
    server:
      process.env.VSCODE_DEBUG &&
      (() => {
        const url = new URL(pkg.debug.env.VITE_DEV_SERVER_URL);
        return {
          host: url.hostname,
          port: +url.port,
        };
      })(),
    clearScreen: false,
  };
});

**Comment by RSS1102** [comment]
you can see it :https://github.com/electron-vite/vite-plugin-electron/issues/48

**Comment by Denhope** [comment]
Thanks,  I 
write

webPreferences: {
      preload,
      nodeIntegration: false,
      contextIsolation: true,
    },
    project build   good,
    but dont work routing and if reload the page i have error

![image](https://github.com/electron-vite/electron-vite-react/assets/70918695/836f7801-502d-4b0c-96f8-7bde22d38766)

**Comment by Denhope** [comment]
Thanks for answers

**Comment by williamtse** [comment]
The problem is related to permissions. Use PowerShell and run npm run build as an administrator.
