### ISSUE TITLE
[Request] Start inner react app

### ISSUE THREAD

**Issue by YeonV** [electron-vite/electron-vite-react#26]
Hi,

first of all THANKS for this amazing project.

Would it be possible to add a `yarn start` script to start the devserver for inner react app without the electron wrapper?

I would like to start and build the web-project isolated (like yarn vite) ontop of the current `yarn dev` and `yarn build` for the electron

as naming, we could also use something like:
`yarn dev:renderer`
`yarn build:renderer`

Thank you soo much
Blade

**Comment by YeonV** [comment]
@caoxiemeihao  YOOOO Thank you soooo much for this wonderful piece!!!

amazing project!! i added some stuff to create a base repo for me aswell:
https://github.com/YeonV/Vitron#vitron

**Comment by caoxiemeihao** [comment]
You're welcome. I'm not familiar with English; I'm glad to help you! 😄
