### ISSUE TITLE
Auto-Build binaries, True DarkMode, CustomTitleBar

### ISSUE THREAD

**Issue by YeonV** [electron-vite/electron-vite-react#29]
Hey, thanks for this amazing project!

I extended some things and created [Vitron](https://github.com/YeonV/Vitron) from it.

Maybe you find my gitactions useful.
- [Auto-Build](https://github.com/YeonV/Vitron/blob/main/.github/workflows/release.yml) win, mac, linux binaries and create a release with autogenerated release-text from git commit messages
- [Auto-Build](https://github.com/YeonV/Vitron/blob/main/.github/workflows/ghpages.yml) and deploy inner react app to github pages

I also added a DarkMode Toggler, which will toggle muiTheme AND nativeTheme (incl. devtools)

as examples I extended your electron-store example and added a Zustand-example.

Custom Title Bar and System Tray can be activated via package.json

You can take anything you want from there. (Would be an honor)
Or ofc you guys can also join Vitron, i will give you access rights directly <3

**Comment by YeonV** [comment]
Also did a create-vitron including customizations like png-to-ico converter :)

`yarn create vitron`
![image](https://user-images.githubusercontent.com/28861537/163098499-6bcfc024-0a7a-4021-9f5c-ec6cbfb0da0e.png)

![image](https://user-images.githubusercontent.com/28861537/163098570-582259b6-b354-4661-8c41-174d9651f5e4.png)

# here are the git actions:
![image](https://user-images.githubusercontent.com/28861537/163098744-156e7ecb-c523-4d2b-9eea-b0096b2481f3.png)
# resulting in an auto-release:
![image](https://user-images.githubusercontent.com/28861537/163098820-3f8a07b1-11b0-4025-9cd2-709238662258.png)

**Comment by caoxiemeihao** [comment]
It looks cool 🎉

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-react/settings/access?query=filter%3Apending_invitations
<img width="761" alt="image" src="https://user-images.githubusercontent.com/26263658/163288627-689571a2-4d07-4205-8209-81e333357777.png">
