### ISSUE TITLE
Window resizing is very laggy

### ISSUE THREAD

**Issue by benjaminroest** [electron-vite/electron-vite-react#30]
Hi, Thanks for your amazing boilerplate!

I noticed that when you resize the window the html on the inside behaves very laggy.

**Comment by PAXANDDOS** [comment]
I've got myself to test it and... is it really laggy? Never seen even a minor lag, and also, I built my own app on top of this template and it also works great. Maybe it's something on your side? @benjaminroest

https://user-images.githubusercontent.com/40315177/179356333-c21c0dc4-7db8-43d5-9da4-02d70378c210.mp4

**Comment by PAXANDDOS** [comment]
Closing as stale. Reopen if the issue still persists.
