### ISSUE TITLE
useEffect bug on dev mode

### ISSUE THREAD

**Issue by ooPG233** [electron-vite/electron-vite-react#33]
在 dev mode 下 
useEffect(() => {
    console.log(111);
 }, [])
似乎会调用两次，打包后是正常的，是什么问题呢

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-react/blob/9a357d858a6940f2375998c795337a5cbdf0febc/packages/renderer/src/main.tsx#L11

`<StrictMode>` 标签去掉试试

```diff
root.render(
-  <StrictMode>
    <App />
-  </StrictMode>
)
```

**Comment by ooPG233** [comment]
> https://github.com/electron-vite/electron-vite-react/blob/9a357d858a6940f2375998c795337a5cbdf0febc/packages/renderer/src/main.tsx#L11
> 
> `<StrictMode>` 标签去掉试试
> 
> ```diff
> root.render(
> -  <StrictMode>
>     <App />
> -  </StrictMode>
> )
> ```

可以了，非常感谢，这是因为什么原因呢

**Comment by caoxiemeihao** [comment]
这个是 React 的机制，要感谢地话，把这几个项目点下 ⭐ 就好。。。
