### ISSUE TITLE
How to specify in `vite.config.ts` file different app for different windows?

### ISSUE THREAD

**Issue by raphael10-collab** [electron-vite/electron-vite-react#37]
How to specify in https://github.com/electron-vite/electron-vite-react/blob/main/vite.config.ts different `apps` each for a different window?

For example:

    /src/app
    /src/app_A 
    /src/app_B

where `App.tsx` and `main.tsx` are in `/src/app` : 

    /src/app/App.tsx
    /src/app/main.tsx 
    
    /src/app_A/App_A.tsx
    /src/app_A/main_A.tsx
    
    /src/app_B/App_B.tsx
    /src/app_B/main_B.tsx

**Comment by caoxiemeihao** [comment]
You may need to create mutilate "html" files.  

e.g.


```diff
  ├─┬ src
+ │ ├── App_A.tsx
+ │ └── App_B.tsx
  ├── index.html
+ ├── app-a.html
+ ├── app-b.html
  └── vite.config.js
``` 

---

**app-a.html**

```html
<html>
  <body>
    <script src="/src/App_A.tsx"></script>
  </body>
</html>
```

**app-b.html**

Such as "app-a.html"

---

**vite.config.ts**

```diff
import { join } from 'path'
import { defineConfig } from 'vite'

export default defineConfig({
  // ...other options
+ build: {
+   rollupOptions: {
+     input: {
+       index: join(__dirname, 'index.html'),
+       App_A: join(__dirname, 'app-a.html'),
+       App_B: join(__dirname, 'app-b.html'),
+     },
+   },
+ },
})
```

---

**electron/main/index.ts**

```ts
import { BrowserWindow } from 'electron'

// index.html
new BrowserWindow().loadURL('http://loaclhost:3000/index.html')

// app-a.html
new BrowserWindow().loadURL('http://loaclhost:3000/app-a.html')

// app-b.html
new BrowserWindow().loadURL('http://loaclhost:3000/app-b.html')
```

**Comment by raphael10-collab** [comment]
Thank you very much @caoxiemeihao

**Comment by raphael10-collab** [comment]
Solved : WindowTypeA.loadURL(url) -> should be WindowTypeA.loadURL(url+'/index_A.html')
