### ISSUE TITLE
importing mongoose issues

### ISSUE THREAD

**Issue by tokochi** [electron-vite/electron-vite-react#41]
I have multiple problems trying to make my electron app work with mongoose, it's work fin in Dev mode but once I try to build it and run it i get a lot of module path errors from mongoose, if i comment this code everything work fine, how I can import mongoose without issues:
```typescript
const mongoose = require("mongoose");
mongoose.connect("mongodb://localhost/arwa")
  .then(() => console.log("Connected to MongoDB..."))
  .catch((err) => console.log("cannot connect to MongoDB", err));
```
![image](https://user-images.githubusercontent.com/79018782/175458076-37e3fb89-4be7-45ce-87c8-9b1a8c260805.png)
![image](https://user-images.githubusercontent.com/79018782/175448056-e231897a-1719-43e3-a676-8b673946379a.png)
![image](https://user-images.githubusercontent.com/79018782/175448553-1bb276d9-94f5-430f-acc6-bb778b47209d.png)

**Comment by caoxiemeihao** [comment]
Can you provide a minimize Demo?

**Comment by tokochi** [comment]
> Can you provide a minimize Demo?

i just used your official repo electron-vite-react without any changes, it work only in dev not in production after i build the app then run :
`npm i mongoose `
after i added this code to electron/main/index.ts:
`const mongoose = require("mongoose");

mongoose
  .connect("mongodb://localhost/arwa")
  .then(() => console.log("Connected to MongoDB..."))
  .catch((err: any) => console.log("cannot connect to MongoDB", err));`
![image](https://user-images.githubusercontent.com/79018782/175537997-f0a1aac5-37d6-439f-875c-b8df37e99b7e.png)
it work only in dev not in production after i build the app

**Comment by caoxiemeihao** [comment]
```diff,ts
+ import { builtinModules } from 'module'      

+ {
+   main: {
+     entry: 'electron/main/index.ts',
+     vite: {
+       build: {
+         sourcemap: false,
+         outDir: 'dist/electron/main',
+         rollupOptions: {
+           external: [
+             'electron',
+             ...builtinModules,
+             // Here
+             'mongoose',
+           ],
+         },
+       },
+     },
+   }
+ } 
```

**Comment by tokochi** [comment]
> ```diff
> import { builtinModules } from 'module' 
> ```

same errors nothing did change, i did add your code in vite.config
```import { rmSync } from "fs";
import { join } from "path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import electron from "vite-plugin-electron";
import renderer from "vite-plugin-electron/renderer";
import pkg from "./package.json";
import { builtinModules } from "module"; 

rmSync(join(__dirname, "dist"), { recursive: true, force: true }); // v14.14.0

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      "@": join(__dirname, "src"),
      styles: join(__dirname, "src/assets/styles"),
    },
  },
  plugins: [
    react(),
    electron({
      main: {
        entry: "electron/main/index.ts",
        vite: {
          build: {
            sourcemap: false,
            outDir: "dist/electron/main",
            rollupOptions: {
              external: [
                "electron",
                ...builtinModules,
                // Here
                "mongoose",
              ],
            },
          },
        },
      },
      preload: {
        input: {
          // You can configure multiple preload scripts here
          splash: join(__dirname, "electron/preload/splash.ts"),
        },
        vite: {
          build: {
            // For debug
            sourcemap: "inline",
            outDir: "dist/electron/preload",
          },
        },
      },
    }),
    // Enables use of Node.js API in the Renderer-process
    renderer(),
  ],
  server: {
    host: pkg.env.VITE_DEV_SERVER_HOST,
    port: pkg.env.VITE_DEV_SERVER_PORT,
  },
});
```

**Comment by caoxiemeihao** [comment]
You must ensure that `mongoose` in `dependencies`

**Comment by tokochi** [comment]
> You must ensure that `mongoose` in `dependencies`

![image](https://user-images.githubusercontent.com/79018782/175761227-4e436ea4-2db8-4790-ab78-611e01aa5140.png)
