### ISSUE TITLE
vite + tailwind + react, css modules dont work everything is global:

### ISSUE THREAD

**Issue by tokochi** [electron-vite/electron-vite-react#44]
i'm actually using vite react and tailwind with default config, this is my `postcss.config.js `  :
``module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
} ``

and I'm also using a syncfusion Grid table that has a built in css classes, since I'm using it in multiple other components, i just wanted to hide this table header in just one react component, so i did add to my component a css file named `noHeaderGrid.module.css`  with this code on it : 
``.e-grid .e-gridheader .e-columnheader{ 
        display: none ; 
    }``
  the style did apply, but to all other grid tables in other component also, why is css modules not working properly, everything is global

**Comment by caoxiemeihao** [comment]
Can you provide a minimize Demo.

**Comment by tokochi** [comment]
i'm using your default `electron-vite-react` template, then i install `npm install -D tailwindcss postcss autoprefixer`, before using tailwind, css modules worked perfectly, each tsx modules has its own css and dont share it with others modules, but now that i have installed tailwind, if i create new css, it globally shared between all modules :
├── src                           react app
│   ├── main.tsx                  
│   ├── App.tsx              className="app"
│               
│       ├── GridTable01.tsx           nested Table component
│       ├── gridTable01.css          i need to hide header just for this grid table add display :none,
                                                    i can even change App background from here, how this is possible 
         │
         ├── GridTable02.tsx          but this one also apply same css and header are also hidden
         ├── GridTable03.tsx           this one also header are hidden

**Comment by PAXANDDOS** [comment]
Can you also provide some source code? And maybe your tailwind config? I'm not sure how you apply classes from CSS in your component and, according to filenames, I'm not sure that you are even using CSS modules. Also, is that the correct folder structure? Seems like `GridTable02.tsx` and `GridTable03.tsx` out of `src` folder.

**Comment by tokochi** [comment]
can you just explain me how to use css module, i did name css file `test.module.css` and import it in my test.tsx component but it not work, why ! vite should support css modules out of the box
