### ISSUE TITLE
Can't use with NextUI or Mantine : Invalid Hook Call

### ISSUE THREAD

**Issue by Guarn** [electron-vite/electron-vite-react#46]
Hey,

I'm trying to use NextUi or Mantine, but I have each time an **Warning: Invalid hook call** :

![image](https://user-images.githubusercontent.com/24851412/179345439-09b8ef30-03cb-47ee-ac0c-de29af8b9a38.png)

It's with simple project setup with nothing else :

![image](https://user-images.githubusercontent.com/24851412/179345693-c14bbe77-98ca-42a2-9272-54c3c4d57dab.png)

### To reproduce
1. `npm install @mantine/core @mantine/hooks`
2. Apply code above

Windows 11

**Comment by anasrar** [comment]
@Guarn install as `devDependencies`

- uninstall first
  `npm uninstall @mantine/core @mantine/hooks`
- install as `devDependencies` with `-D`
  `npm install -D @mantine/core @mantine/hooks`

https://github.com/electron-vite/vite-plugin-electron-renderer#dependencies-vs-devdependencies
