### ISSUE TITLE
Unexpected token 'delete'. Error useing axios

### ISSUE THREAD

**Issue by huanglong6828** [electron-vite/electron-vite-react#48]
Uncaught SyntaxError: Unexpected token 'delete' (at __x00__axios:6:14)

![image](https://user-images.githubusercontent.com/19216952/179875613-b024048a-657d-4f42-8036-34d336c186cc.png)

**Comment by caoxiemeihao** [comment]
关键字没过滤，导出有问题啊 😅

**Comment by huanglong6828** [comment]
好的 大佬 给大佬刷个🚀

**Comment by caoxiemeihao** [comment]
Now, `vite-plugin-electron@v0.8.1` is available.
