### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by Cuppachino** [electron-vite/electron-vite-react#50]
![electron-vite dev server error](https://user-images.githubusercontent.com/92656523/180424501-b3705315-6ff7-4092-a724-98474ddc35fe.png)
![electron-vite dev server error2](https://user-images.githubusercontent.com/92656523/180424723-4634af5a-bae8-4795-9f7c-ea37c9ab967d.png)
)
- Windows 11 Pro 10.0.22621 Build 22521
- Node 16.13.2

**Comment by PAXANDDOS** [comment]
I faced no issues when running the application with your setup. Maybe you can provide some of your code if you have added/modified it? 

I also have Windows 11 of the latest build and installed your Node version from its distros. Though I would recommend updating your Node.js to the LTS version at least. 

Also `electron-vite-react` recently received some updates and it would be good if you could fresh-clone and start over.

**Comment by Cuppachino** [comment]
I updated node to 16.16.0 and created a new project from the template and its working. Thank you very much. Sorry for the silly issue.

**Comment by Cuppachino** [comment]
I'm reopening because this is still a problem. I've tested it with Node 16.16.0 and 18.6.0 on Windows. Usage of ipcRenderer in the renderer process causes this error in browsers:
![image](https://user-images.githubusercontent.com/92656523/181006755-d3de7b0e-5c7f-4ad0-afb2-b7460e5ebcde.png)

steps to reproduce:
1. create a fresh project with `npm create electron-vite`
2. in main.tsx, uncomment `import "./samples/node-api"`

Maybe I am missing something. What is the recommended approach for sending messages between the main & renderer processes without breaking browser support?

**Comment by Cuppachino** [comment]
I was able to get it working by enabling the contextBridge and extending the global Window interface.

```typescript
// electron > main > index.ts
win = new BrowserWindow({
  title: "Main window",
  icon: join(ROOT_PATH.public, "favicon.svg"),
  webPreferences: {
    preload,
    nodeIntegration: true,
    contextIsolation: true,
  },
});
  ```
  ```typescript
  // electron > preload > index.ts
contextBridge.exposeInMainWorld("ipc", {
  send: (channel: EventChannel, ...args: any[]) =>
    ipcRenderer.send(channel, ...args),
  on: (channel: EventChannel, func: (...args: any[]) => void) =>
    ipcRenderer.on(channel, (event, ...args) => func(...args)),
});
```
example with typings:
```typescript
// src > types > global.d.ts
declare global {
  type EventChannel = "main-process-message" | "window-event";

  type WindowEvent =
    | "focus"
    | "blur"
    | "close"
    | "minimize"
    | "maximize"
    | "unmaximize";

  type EventMessage<Channel extends EventChannel> =
    Channel extends "window-event"
      ? WindowEvent
      : Channel extends "main-process-message"
      ? string
      : any;

  type EventHandler<Channel extends EventChannel> = (
    type: EventMessage<Channel>
  ) => void;

  interface Window {
    ipc: {
      send: <Channel extends EventChannel>(
        channel: Channel,
        msg: EventMessage<Channel>
      ) => void;
      on: <Channel extends EventChannel>(
        channel: Channel,
        handler: EventHandler<Channel>
      ) => Electron.IpcRenderer;
    };
  }
}

export {};
```
```typescript
// src > samples > node-api.ts
// IDE recognizes args as type 'WindowEvent'
window.ipc?.on("window-event", (args) => {
  console.log(args);
  // => "focus" | "blur" | "close" ...etc
});
```

**Comment by PAXANDDOS** [comment]
@caoxiemeihao I guess your help will be needed here. I have always been working with `ipcRenderer` by passing its functionality in contextBridge. You implemented the feature to use it directly in renderer so you know better 😅 

As about contextBridge, @Cuppachino. It is actually considered a more secure way to write the application (if it interacts with third-party services/websites). If you're going that way, don't forget to [remove the `renderer` option in `vite.config.ts`](https://github.com/electron-vite/electron-vite-react#-be-aware), and also you can turn off `nodeIntegration` as in your example:
```diff
// electron > main > index.ts
win = new BrowserWindow({
  title: "Main window",
  icon: join(ROOT_PATH.public, "favicon.svg"),
  webPreferences: {
    preload,
-   nodeIntegration: true,
+   nodeIntegration: false,
    contextIsolation: true,
  },
});
```
None of them is an "intended approach", people can use `contextBridge` and can not, it all depends on what their application does and on their considerations. I'm not sure why direct import of `ipcRenderer` causes errors, will take a look when I have time, but maybe @caoxiemeihao knows better

**Comment by caoxiemeihao** [comment]
## English

I think you are a developer new to Electron

First of all you need to determine whether you need to use the Node.js/Electron API in the Renderer-process, if you want to use them in the Renderer-process, then you need to do the following two things

1. Enable Renderer-process support in `vite-plugin-electron`

```diff
# vite.config.ts

electron({
+ renderer: {}
})
```

2. Enable Node.js integration in the Main-process

```diff
webPreferences: {
+  nodeIntegration: true
}
```

```js
// src/main.tsx
import { ipcRenderer } from 'electron'
// ✅ work normally
```

---

For security reasons you don't want to use the Node.js/Electron API in the Renderer-process, then you need to pay attention to the following

1. Don't use `ipcRenderer` directly in the Renderer-process because it means you want to use the Node.js/Electron API in the renderer - **this is important**

```js
// src/main.tsx
import { ipcRenderer } from 'electron'
// ❌ Please don't do this, it means you are using the Node.js API
```

2. Remove Node.js integration in Main-process

```diff
webPreferences: {
-  nodeIntegration: true
}
```

3. Remove the Renderer configuration in `vite-plugin-electron`

```diff
# vite.config.ts

electron({
- renderer: {}
})
```

4. Serving `ipcRenderer` via Preload-script

see [preload/index.ts](https://github.com/electron-vite/electron-vite-react/blob/0558371af68b1ed432c3269d919b971f1403e736/packages/preload/index.ts)

```js
// electron/preload.ts
import { contextBridge, ipcRenderer } from 'electron'
contextBridge.exposeInMainWorld('ipcRenderer', ipcRenderer)
```

see [preload-module.ts](https://github.com/electron-vite/electron-vite-react/blob/0558371af68b1ed432c3269d919b971f1403e736/packages/renderer/src/samples/preload-module.ts)

```js
// src/main.tsx
window.ipcRenderer.on('main-process-message', (event) => { console.log(event) })
```

see [global.d.ts](https://github.com/electron-vite/electron-vite-react/blob/0558371af68b1ed432c3269d919b971f1403e736/packages/renderer/src/global.d.ts)

```js
// src/electron-env.d.ts(need create)
export { }
declare global {
  interface Window {
    // Expose some Api through preload script
    fs: typeof import('fs')
    ipcRenderer: import('electron').IpcRenderer
    removeLoading: () => void
  }
}
```

---

1. `require is not defined` Because you are using the Node.js API in the Renderer-process but not enabling the Node.js integration option in the Main-process
2. `samples/node-api` is the example code to enable Node.js API integration, if you don't understand it, then don't use it.


---
---


## 简体中文

我想你是个刚刚接触 Electron 没多长时间的开发者

首先你需要明确你是否需要在渲染进程中使用 Node.js/Electron API，如果你希望在渲染进程中使用它们，那么你要做到下面两点

1. 在 vite-plugin-electron 中开启渲染进程支持

```diff
# vite.config.ts

electron({
+ renderer: {}
})
```

2. 在主进程中开启 Node.js 集成

```diff
webPreferences: {
+  nodeIntegration: true
}
```

```js
// src/main.tsx
import { ipcRenderer } from 'electron'
// ✅ work normally
```

---


相反的，出于安全的考虑你不希望在渲染进程中使用 Node.js/Electron API，那么你需要注意如下几点

1. 不要直接在渲染进程中使用 ipcRenderer，因为它代表你想要在渲染进程使用 Node.js/Electron API - **这个很重要**

```js
// src/main.tsx
import { ipcRenderer } from 'electron'
// ❌ 请不要这样做，这代表你使用了 Node.js API
```

2. 移除主进程中关于 Node.js 集成的配置

```diff
webPreferences: {
-  nodeIntegration: true
}
```

3. 将 vite-plugin-electron 中的渲染进程配置移除

```diff
# vite.config.ts

electron({
- renderer: {}
})
```

4. ipcRenderer 功能将通过 preload 脚本提供

see [preload/index.ts](https://github.com/electron-vite/electron-vite-react/blob/0558371af68b1ed432c3269d919b971f1403e736/packages/preload/index.ts)

```js
// electron/preload.ts
import { contextBridge, ipcRenderer } from 'electron'
contextBridge.exposeInMainWorld('ipcRenderer', ipcRenderer)
```

see [preload-module.ts](https://github.com/electron-vite/electron-vite-react/blob/0558371af68b1ed432c3269d919b971f1403e736/packages/renderer/src/samples/preload-module.ts)

```js
// src/main.tsx
window.ipcRenderer.on('main-process-message', (event) => { console.log(event) })
```

see [global.d.ts](https://github.com/electron-vite/electron-vite-react/blob/0558371af68b1ed432c3269d919b971f1403e736/packages/renderer/src/global.d.ts)

```js
// src/electron-env.d.ts(need create)
export { }
declare global {
  interface Window {
    // Expose some Api through preload script
    fs: typeof import('fs')
    ipcRenderer: import('electron').IpcRenderer
    removeLoading: () => void
  }
}
```

---

1. `require is not defined` 因为你在渲染进程中使用了 Node.js API 但是没有在主进程中开启 Node.js 集成选项
2. `samples/node-api` 是开启 Node.js API 集成的实例代码，如果你弄不明白它，那么不要使用它

**Comment by PAXANDDOS** [comment]
> 1. create a fresh project with `npm create electron-vite`
> 2. in main.tsx, uncomment `import "./samples/node-api"`

I managed to reproduce your steps (Sorry that took really long 😅) and... everything works fine?

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/40315177/181906265-d1dacd27-64b2-4891-a990-1e9453493f00.png" />
</details>

I mean you must have forgotten to turn something on. Again my environment is `Windows 11 Home` of latest build and `Node.js v18.6.0` and everything works fine

What @caoxiemeihao said is how to configure application for use in both ways, but I believe you already found your way. What I wanted to add to his words is that you should also turn on `contextIsolation` when using `contextBridge` and turn off when not and that's it. 

@Cuppachino What's your current status with the problem?

**Comment by Cuppachino** [comment]
@caoxiemeihao I've only been working with electron for the past couple of months, so your guess isn't too far off! I think what you have written here will be very helpful to new devs. 

@PAXANDDOS the issue is when using the first method, the default method, and expecting the app to load in browser during dev.
```
steps to reproduce:
1. create a fresh project with `npm create electron-vite`
2. in main.tsx, uncomment `import "./samples/node-api"`
3. open chrome or firefox
4. navigate to localhost:7777
```

I don't think we should say "use `contextIsolation` & `contextBridge` for security reasons..." if NOT using them means losing access to dev tool extensions unsupported by electron.

**Comment by caoxiemeihao** [comment]
I will plan to write a very detailed document, which will be time consuming work.

**Comment by ashen114** [comment]
引入‘electron-store’的问题：

代码片段：

electron\main\index.ts
```ts
    webPreferences: {
      webSecurity: false, // 允许跨域请求
      preload,
      nodeIntegration: true,
      contextIsolation: true,
    },
```

electron\preload\index.ts
```ts
import { contextBridge } from 'electron'
import Store from 'electron-store'

const store = new Store()

contextBridge.exposeInMainWorld('store', {
  get: (key) => store.get(key),
  set: (key, value) => {
    store.set(key, value)
  }
})
```

vite.config.ts
```
  plugins: [
    react(),
    electron({
      main: {
        entry: 'electron/main/index.ts',
        vite: withDebug({
          build: {
            outDir: 'dist/electron/main',
          },
        }),
      },
      preload: {
        input: {
          // You can configure multiple preload scripts here
          index: join(__dirname, 'electron/preload/index.ts'),
        },
        vite: {
          build: {
            // For debug
            sourcemap: 'inline',
            outDir: 'dist/electron/preload',
          }
        },
      },
      // Enables use of Node.js API in the Electron-Renderer
      renderer: {}
    }),
    createStyleImportPlugin({
      resolves: [AntdResolve()], libs: [
        // If you don’t have the resolve you need, you can write it directly in the lib, or you can provide us with PR
        {
          libraryName: 'antd',
          esModule: true,
          resolveStyle: (name) => {
            return `antd/es/${name}/style/index`
          },
        },
      ],
    })
  ],
```

结果：```Uncaught ReferenceError: require is not defined  at promises:1:13```
![image](https://user-images.githubusercontent.com/28629247/182070292-81fe32db-89e0-4159-ab4c-ec1e1c8e1183.png)
![image](https://user-images.githubusercontent.com/28629247/182070320-7b87cb34-f882-47a6-b1c0-e478540931e1.png)

**Comment by PAXANDDOS** [comment]
Issue resolved? 👀 @Cuppachino

**Comment by EliasLeguizamon123** [comment]
Hi everyone, i have similar issue here, im trying to send message from main process to renderer process, so i defined this :
```
// defined win BrowserWindow
win = new BrowserWindow({
        title: 'Main window',
        icon: join(ROOT_PATH.public, 'favicon.svg'),
        show: false,
        frame: false,
        resizable: true,
        webPreferences: {
            preload,
            nodeIntegration: false,
            contextIsolation: true,
        },
    });
    .....
// Send message to preload
win.webContents.send('token', `{ token: ${json.token} }`);
```

So, in preload i define my context Bridge like always:

```
import { contextBridge, ipcRenderer } from 'electron';

const api = {
    token: (data) => ipcRenderer.on('token', data),
};

contextBridge.exposeInMainWorld('api', api);

```
I'm reading above on this problem and from what I understand I also need to declare this for typescript:

```
export {};

declare global {
    interface Window {
        api: any;  // I don't know if i defined correctly maybe my error is here
    }
}
```
So, my final file is renderer process: 

```
export default function App() {
    console.log('token', window.api.token); //this don't return error simplely return the image below

    return (
        <Box>
            <Router />
        </Box>
    );
}
```
finally my console return this, not exactly an error but it doesn't return my main message either
![error](https://user-images.githubusercontent.com/25516473/191038315-389eb70e-26fb-44b6-b1fd-983e6d17fb01.png)

**Comment by caoxiemeihao** [comment]
contextBridge.exposeInMainWorld(window, { api });

**Comment by spmonahan** [comment]
@caoxiemeihao [Your explanation here](https://github.com/electron-vite/electron-vite-react/issues/50#issuecomment-1196159013) was really helpful! Please consider making a demo with this configuration or linking to the document from the README. It took me awhile to find your comment but once I did I was able to quickly get the context bridge working.

**Comment by caoxiemeihao** [comment]
@spmonahan okay!
I plan to do better in subsequent [vite-plugin-electron-renderer](https://github.com/electron-vite/vite-plugin-electron-renderer) versions and prompt users directly in the console how to resolve it.
