### ISSUE TITLE
[bug]: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by Cnotech** [electron-vite/electron-vite-react#52]
## Screenshort
![image](https://user-images.githubusercontent.com/53827731/180609163-3de136d7-ca18-4794-9346-bdab42f10bf8.png)
![image](https://user-images.githubusercontent.com/53827731/180609195-b8c313e9-f6d5-4a35-a2d4-452a025002f0.png)

The images in the development are work normally, which is presumed to be caused by the BUG of processing dynaimc-import images when Vite is built.

*在开发环境图片正常显示，推测是 vite 构建时处理动态引入的图片出现问题导致的*

## Reproduce
- System: Windows
- Clone this repository, exec `yarn && yarn build`
- cd `./release/2.0.0/win-unpacked`, click and run `YourAppName.exe`

**Comment by caoxiemeihao** [comment]
Thanks feedback :)
This BUG currently occurs in Vite 3.x, temporarily consider downgrading to Vite 2.x.  
I will consider submitting an Issue or PR to Vite.

**Comment by caoxiemeihao** [comment]
We will discuss it in this issue 👉 https://github.com/electron-vite/electron-vite-vue/issues/212

**Comment by caoxiemeihao** [comment]
@Cnotech ! 👋
This BUG will be fixed in https://github.com/electron-vite/electron-vite-react/pull/55
Nevertheless, experimental.renderBuiltUrl is currently an experimental API.
Looking forward to the next update of Vite.
