### ISSUE TITLE
Be Aware - Node.js API in the Electron rendering process

### ISSUE THREAD

**Issue by npearson72** [electron-vite/electron-vite-react#56]
I have a question about this issue:

https://github.com/electron-vite/electron-vite-react#-be-aware

Does this issue only impact apps that intend to use the local file system and other Node.js APIs, or does this issue impact any usage of Vite with Electron?

For example, can the integration be disabled for thin client apps that will be talking to a remote server?

**Comment by caoxiemeihao** [comment]
It just intercepts Node.js/Electron modules and translates them into ESM modules.

https://github.com/electron-vite/vite-plugin-electron/tree/main/packages/electron-renderer#electron-renderervite-serve

**Comment by npearson72** [comment]
Ok, got it. Thank you.
