### ISSUE TITLE
rollup uses require() with multiple inputs

### ISSUE THREAD

**Issue by Kilian** [electron-vite/electron-vite-react#58]
When building an app with multiple inputs:

```js
build: {
  rollupOptions: {
    input: {
      index: path.resolve(__dirname, 'index.html'),
      panel: path.resolve(__dirname, 'panel.html')
    }
  }
},
```
rollup automatically creates a shared `app.<hash>.js` file with all the common modules and requires it from both entry files. 

However with Electron properly configured, `require` is not available in the renderer, so the app doesn't work. What is the correct way to make this work, either by inlining the common modules in both (larger file size) or selectively allowing require (I'd rather not?).

**Comment by caoxiemeihao** [comment]
May be neet turn off the following options.
https://github.com/electron-vite/electron-vite-react/blob/63cef8829995d1309acbc4a799240cfca177f9e4/vite.config.ts#L48
This options will cause Rollup to build code in `cjs` format. 👉 [Config presets (Opinionated)](https://github.com/electron-vite/vite-plugin-electron/tree/main/packages/electron-renderer#config-presets-opinionated)
After removing this option, Rollup will use the `esm` format to build the code by default, which can avoid the `require` in the bundle code.

**Comment by Kilian** [comment]
Unfortunately, some of Electrons scripts use `path` and those (specifically, `node_modules/electron/index.js`) get included into the `app.<hash>.js` bundle, causing an error because path is not available with node integration turned off.

**Comment by caoxiemeihao** [comment]
In fact, if `nodeIntegration` is not enabled, even the `require` function cannot be used, although we can use the following to avoid Vite [Pre-Bundling](https://vitejs.dev/guide/dep-pre-bundling.html) `node_modules/electron/index.js`, but in the where the `require` function is not available Down. We still can't use any exported members of `electron`.

```js
const { nativeTheme } = require('electron')
// Uncaught ReferenceError: require is not defined
```

**Comment by caoxiemeihao** [comment]
Now `electron-vite-react@2.1.0` is based on the `vite-electron-plugin`, This is broke!
