### ISSUE TITLE
window.electronAPI is undefined

### ISSUE THREAD

**Issue by xiaokinglong** [electron-vite/electron-vite-react#60]
在页面无法获取到 window.electronAPI

**Comment by caoxiemeihao** [comment]
`electronAPI` 是 Electron 提供的 API?

**Comment by xiaokinglong** [comment]
我的问题描述的有问题  就是怎么进行通信？ 我在preload 写的方法 在页面中通过 window.electronAPI 调用是 undefined的

```js
const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("electronAPI", {
    setTitle: (title) => ipcRenderer.send("send-message", title),
});
```

**Comment by caoxiemeihao** [comment]
你在主进程中开启 Node.js 集成了么？

**Comment by xiaokinglong** [comment]
这个需要在vite.config.ts中配置吗

**Comment by caoxiemeihao** [comment]
模板默认就是开启的，你多去百度下 Electron 相关的方面。

**Comment by fellipeParreiras** [comment]
> 你在主进程中开启 Node.js 集成了么？

I have the same issue. I've tried with `nodeIntegration = true` and `contextIsolation` in all possible truth states. I simply cannot get ipcRenderer or any exposed API in the browser environment. Even a minimal setup with `npm create electron-vite`, without changing anything, gives an error related to ipcRenderer on `main.tsx`.
I would appreciate some assistance. <3
