### ISSUE TITLE
linux icon is not working

### ISSUE THREAD

**Issue by lifeiscontent** [electron-vite/electron-vite-react#63]
Hi, thanks for your hard work on this template. I was wondering if you could point out how to add a linux icon here?

Thanks again!

**Comment by lifeiscontent** [comment]
one other note is when I run `npm run build` I notice in the release folder it produces a folder that looks like this:

```
release
  - ${version} // this is the actual name
    icon_16x16.png
    icon_....png
```

**Comment by PAXANDDOS** [comment]
Hey @lifeiscontent! Seems like `electron-builder` had an update where Linux builds are not using `.ico` files anymore. I will take a better look on weekend but seems like you just have to add PNG files to the resources and change the configuration. Please take a look at the [electron-builder configuration reference](https://www.electron.build/configuration/linux)

**Comment by lifeiscontent** [comment]
@PAXANDDOS I've dug into it a bit and even setting the png file directly as: `electron/resources/icon/256x256.png` does not work, I've got target set to AppImage, just for context, but for the life of me I have yet to figure this one out, so any help here would be much appreciated!

**Comment by PAXANDDOS** [comment]
You specified the path as `electron/resources/icon/256x256.png` but you forgot the `s`, documentation says it should be `electron/icons/*` unless changed in the electon-builder config. You can also place a single `icon.png` under `resources`.

But they also say that the best way to add Linux icons is to use macOS icons. Linux icon set will be generated automatically based on the macOS `icns` file or common icon.png. You can use any online convert tool to make your icns.

**Comment by lifeiscontent** [comment]
@PAXANDDOS I've tried doing both of those and they don't work, you can see the project here: https://github.com/bitgo/wallet-recovery-wizard/tree/fresh-start

**Comment by lifeiscontent** [comment]
but also, the template doesn't have an icon for linux AppImages either

**Comment by PAXANDDOS** [comment]
That's pretty strange since build resources are specified explicitly. We'll take a note, thanks so much for investigating! ❤️
