### ISSUE TITLE
hmr not working with jsx

### ISSUE THREAD

**Issue by AhmedRyad22** [electron-vite/electron-vite-react#65]
by working on jsx it seems like vite is not detecting any changes at all , any thing to add to config ?

**Comment by PAXANDDOS** [comment]
Can you please do reproduction steps? Or even better an archive with your example. If you just changed tsx to jsx then it should work.

**Comment by AhmedRyad22** [comment]
finally found it, i hade a file named Home.jsx inside a folder named Components, but was importing like this:
`import Home from './components/Home'` notice the C became c.
in import it works, but in HMR it was not beeing detected.

thanx btw .
