### ISSUE TITLE
 After the main thread references the electron-store, the dependency is lost

### ISSUE THREAD

**Issue by Mychen3** [electron-vite/electron-vite-react#66]
Greetings,
I need some help 🙏

**Normal in dev mode, lost after packaging**

`
  "dependencies": {

    "electron-store": "^8.1.0",

  },
`

![(_464_ ZWI)VUF6COQNZL~Y](https://user-images.githubusercontent.com/65877592/189495496-23cea83c-08d4-449b-ad05-5452304bbbbc.png)

**It is these dependencies that are not found in the source code in the electronic store**

![3HG`UM$N XYXQZ`BB AN7 5](https://user-images.githubusercontent.com/65877592/189495316-2c4b79c3-f164-4da3-87a5-ce59f57f83bc.png)

**Comment by Mychen3** [comment]
Vite doesn't seem to pack the dependencies

**Comment by caoxiemeihao** [comment]
Maybe this issues will be usefuf to you.
https://github.com/electron-vite/electron-vite-vue/issues/253

**Comment by Mychen3** [comment]
> 也许这个问题对你有用。 [电子-vite/电子-vite-vue#253](https://github.com/electron-vite/electron-vite-vue/issues/253)

非常感谢，使用 pnpm i --shamefully-hoist 就可以了，是因为vite的 tree shaking导致的吗？
