### ISSUE TITLE
worker文件应该放在哪里呢

### ISSUE THREAD

**Issue by liuyike98** [electron-vite/electron-vite-react#69]
preload有单独的文件夹，worker文件是否应该也有单独的文件夹进行编译输出呢，vite不是很熟悉

**Comment by caoxiemeihao** [comment]
你是要用在 Main 中还是要用在 Preload 中？

**Comment by liuyike98** [comment]
> 你是要用在 Main 中还是要用在 Preload 中？要么你试试 https://github.com/electron-vite/vite-electron-plugin 这个插件，不区分 Preload、Main 这种文件夹，一把梭。

试了下你的新插件，可以分目录编译，就像tsc一样，但是好像连d.ts都编译成d.js了，虽然是空文件

**Comment by caoxiemeihao** [comment]
> 试了下你的新插件，可以分目录编译，就像tsc一样，但是好像连d.ts都编译成d.js了，虽然是空文件

感觉咋样？是不是比这个更快、比这个更符合直觉？
有打算再稍微稳定点把这个项目的 `vite-plugin-electron` 换成 `vite-electron-plugin`

**Comment by liuyike98** [comment]
> > 试了下你的新插件，可以分目录编译，就像tsc一样，但是好像连d.ts都编译成d.js了，虽然是空文件
> 
> 感觉咋样？是不是比这个更快？比这个更符合直觉？ 有打算再稍微稳定点把这个项目的 `vite-plugin-electron` 换成 `vite-electron-plugin`
> 
> **`xxx.d.ts` 那个是小 BUG**

正在体验中哈哈，感觉想法很棒

**Comment by mundane799699** [comment]
想请教一下，worker文件应该怎样配置，才能在dist-electron中生成worker.js文件？
