### ISSUE TITLE
vite-electron-plugin 替代vite-plugin-electron之后，nodejs的配置丢失

### ISSUE THREAD

**Issue by jaw52** [electron-vite/electron-vite-react#73]
最新创建的项目升级到`vite-electron-plugin `之后，在react应用内部使用nodejs Api行不通了

**Comment by jaw52** [comment]
顺便问一下，后面的更新都会以`vite-electron-plugin`为基础了，抛弃之前的`vite-plugin-electron`了吗

**Comment by caoxiemeihao** [comment]
使用 NodeJs API 装下 vite-plugin-electron-renderer

两个插件定位不同，互补关系，Vite-electron-plugin 性能更好
