### ISSUE TITLE
代码混淆

### ISSUE THREAD

**Issue by liuyike98** [electron-vite/electron-vite-react#74]
现在的版本换用了新的electron vite插件，但是注意到打包后没有进行任何的混淆，几乎就是源代码没动，是否计划支持混淆呢？

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-electron-plugin#electronconfig-configuration

<img width="851" alt="image" src="https://user-images.githubusercontent.com/26263658/195038247-6eba04e1-168e-4620-a475-133f6da4fb1a.png">
