### ISSUE TITLE
Entry point is invalid and release version is not working (Windows 11)

### ISSUE THREAD

**Issue by fs86** [electron-vite/electron-vite-react#75]
**Issue 1:**
The entry point is "dist-electron/main/index.js" but should be "dist-electron/electron/main/index.js" i guess?
![issue1](https://user-images.githubusercontent.com/39554311/196275461-38c6281d-8f7e-4a6c-9e0a-1262b487a24f.png)

**Issue 2:**
Once I change the entry point I can start the application in development mode but the release version which I created with `yarn build` won't start. It shows the following error message:
```
(node:24752) electron: Failed to load URL: file:///D:/electron-vite-react/release/2.1.0/win-unpacked/resources/app.asar/dist-electron/dist/index.html with error: ERR_FILE_NOT_FOUND
(Use `YourAppName --trace-warnings ...` to show where the warning was created)
```

**Comment by caoxiemeihao** [comment]
**Issue 1:**
https://github.com/electron-vite/vite-electron-plugin/blob/5dd82a3ee5db6bd484f8b6ae66794b309b2e34d4/src/config.ts#L214-L227

<img width="637" alt="image" src="https://user-images.githubusercontent.com/26263658/196308121-57f65ee6-3545-4041-a90e-a3338197009e.png">

The behavior like `tsc`.

**Issue 2:**
You must adjust according to the new build directory structure.

https://github.com/electron-vite/electron-vite-react/blob/d6f989c4f5099dbd84dc54fe3d7dc9a92d6691bc/electron/main/index.ts#L1-L13

**Comment by fs86** [comment]
@caoxiemeihao Thank you for your answer. If I understand it correctly, I have to adjust the entry point (main) to "dist-electron/electron/main/index.js" if I want to use preload.ts, right? At least this seems to work.

Unfortunately I cannot solve Issue 2. Can you please assist me with this one? I've printed out the directories in dev and release version to see what's going on but I don't know how I have to adjust the directories to get the release version working as well. Please see screenshots below:
![dev](https://user-images.githubusercontent.com/39554311/196354745-30da0212-d303-4ee9-a8e5-3d126d0cddd4.jpg)
![release](https://user-images.githubusercontent.com/39554311/196354767-95babd41-7622-4c3a-b41d-ae764f680383.jpg)

Thank you in advance.

**Comment by caoxiemeihao** [comment]
```diff
- process.env.DIST_ELECTRON = join(__dirname, '..')
+ process.env.DIST_ELECTRON = join(__dirname, '../..')
```

**Comment by fs86** [comment]
Okay, thank you very much!

**Comment by juandl** [comment]
I believe this is still happening on win 11

`(node:24688) electron: Failed to load URL: file:///C:/Users/USER/AppData/Local/Programs/electron-vite-react/resources/app.asar/dist/index.html with error: ERR_FILE_NOT_FOUND`

**Comment by caoxiemeihao** [comment]
@juandl Is this caused ba upgrading the `vite-plugin-electron` version?
