### ISSUE TITLE
Release Build fails

### ISSUE THREAD

**Issue by wouterverweirder** [electron-vite/electron-vite-react#76]
This issue consists of 2 parts: build command failing & release build not working. Tested on macOS Monterey M1.

1. The entry point definition in the package.json file is wrong, which causes the build command to fail. It currently states:

https://github.com/electron-vite/electron-vite-react/blob/d6f989c4f5099dbd84dc54fe3d7dc9a92d6691bc/package.json#L9

But should be

```
"main": "dist-electron/electron/main/index.js",
```

After making that adjustment, the build command succeeds, however, the release does not work and shows the following error in the dev tools:

```
Not allowed to load local resource: file:///Users/wouter/Documents/demo/electron-vite-react/release/2.1.0/mac-arm64/YourAppName.app/Contents/Resources/app.asar/dist-electron/dist/index.html
```

**Comment by wouterverweirder** [comment]
Extacting the asar file tells me that the index.html file sits in

```
app.asar/dist/dist/index.html
```

instead of 

```
app.asar/dist-electron/dist/index.html
```

**Comment by caoxiemeihao** [comment]
Thanks for you feedback! Fixed it.
