### ISSUE TITLE
Images do not load properly when example app is built.

### ISSUE THREAD

**Issue by gfrung4** [electron-vite/electron-vite-react#78]
1. Clone this repository.
2. In the directory containing the cloned files, run `npm install`.
3. Now run `npm run dev`.  Note the app starts and looks like this:

![image](https://user-images.githubusercontent.com/1622067/197539248-552d4ce6-931e-4ffc-92b6-7ba7e22ec2ed.png)

4. Now run `npm run build` and locate the build output in the **release/2.1.0** folder.  Run the app from here and it looks like this:

![image](https://user-images.githubusercontent.com/1622067/197539259-d2d8b285-872c-47a6-8041-e7b8010f291e.png)

The spinning images at the top do not load correctly once the app is built.  This occurs when using this repository's files without modification, so there is a bug in the example.

**Comment by debugksir** [comment]
同样的问题，求解决方案
