### ISSUE TITLE
Way to share code between main process and render process

### ISSUE THREAD

**Issue by rapiz1** [electron-vite/electron-vite-react#83]
I wonder if there's way to share code between main process and render process

e.g. a `common` under the root so main and render can both import `common/something`

**Comment by caoxiemeihao** [comment]
Yep! The files in `common` folder,  can be imported by both `main` and `renderer`. But they are not interoperable, but exist independently in `main` and `renderer`.

**Comment by BadarSaghir** [comment]
Adding alias in vite.config can solve this issue, for we can add alias "~"  to folder "common" as like this
```
resolve: {
      alias: {
      
        "~": path.resolve(__dirname, "common"),


      },
    },
    
```

than you can import it like this
import abc from "~/myfile"

**Comment by GimpMaster** [comment]
Sorry to comment on a closed thread but I tried this approach and I keep getting startup errors when running `yarn dev`

What I did was create a `common` folder in the root

```
/src <--- render app
/electron <--- main process
/common/test.ts <--- contains an interface I want
```

Then I include this in `/electron/main.ts`

```
import Test from "../../common/test";
```

PHP Storm isn't happy and neither is vite. I get the following error.

```
Uncaught Exception:
Error: Cannot find module '../../common/test'
Require stack:
- /home/blah/test-fixture-app/dist-electron/main/index.js
```

I then tried adding `common` to include in tsconfig.json. 

```
"include": ["src", "common"]
```

as well as in tsconfig.node.json

`"include": ["vite.config.ts", "package.json", "electron", "common"]`

I'm guessing it has something to do with vite.config.json for electron but I'm not sure. Any thoughts?

**Comment by GimpMaster** [comment]
@caoxiemeihao

**Comment by GimpMaster** [comment]
If I add to the electron config in vite.config.js like this


```
include: [
          'electron',
         'common'
        ],
```

what happens is now the electron and common are in the same dist-electron folder and vite fails to find main.js

**Comment by GimpMaster** [comment]
Ok, I think I got it by setting package.json to this...

`"main": "dist-electron/electron/main/index.js",`

**Comment by caoxiemeihao** [comment]
@GimpMaster Provide a minimal reproduction repo?

**Comment by GimpMaster** [comment]
@caoxiemeihao - The issue doesn't show up if its just simple interfaces that get removed from compiling, but if you create lets say an enum which you then use that object doesn't get created since tsconfig isn't compiling common.

Here is a repo where its failing...

https://github.com/GimpMaster/electron-vite-react-issue

notice the common folder with test.ts

**Comment by caoxiemeihao** [comment]
@GimpMaster It's just a matter of config.

Repository https://github.com/GimpMaster/electron-vite-react-issue needs come options changs.

vite.config.ts

```diff
  electron({
    include: [
-     'electron'
+     'electron',
+     'common',
    ],
    // ...others
  })
```
package.json

```diff
- "main": "dist-electron/main/index.js",
+ "main": "dist-electron/electron/main/index.js",
```

**Comment by GimpMaster** [comment]
Thank you @caoxiemeihao - Yes that is what I found. It would be cool to update the template to have this common folder with examples.

One thing I would love to get your feedback on is I was able to add an alias of `~` to point to the common folder as was mentioned above, but when I run `yarn dev` It fails to startup saying it can't resolve `~/test`. 

I added the path to both tsconfig.json and tsconfig.node.json as well as updated vite.config.js with the alias.

Any thoughts on that? It works fine in the rendering process.

**Comment by caoxiemeihao** [comment]
```js
resolve: {
  alias: {
    '～': __dirname,
  },
}
```
Does it not work? This is Vite's configuration, not the `vite-electron-plugin`.
You should check the Vite document.

**Comment by GimpMaster** [comment]
Yeah I'm doing this...

```
resolve: {
      alias: {
        '@': path.join(__dirname, 'src'),
        '~': path.join(__dirname, 'common')
      },
    },
```

and the ~ works in the renderer process but fails in the main process. I'm not sure if the main process is ran through Vite or not.

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-electron-plugin/tree/main/examples%2Falias

**Comment by GimpMaster** [comment]
I just wanted to leave a comment on here that if you want to use alias in BOTH render and main process you have to use the following...

```
// Main vite.config.ts return object
	return {
		resolve: {
			// This alias is for Renderer-process, not for Electron-Main
			alias: {
				'@': path.join(__dirname, 'src'),
				'~': path.join(__dirname, 'common')
			}
		},


// inside electron plugin
		plugins: [
			react(),
			electron({
                                        // ...
					// This alias is for Electron-Main, not for Renderer-process
					alias([
						{
							find: '~',
							replacement: path.join(__dirname, 'common')
						}
					])
				]
			}),
```

With both those changes I was able to use alias for render and main process

**Comment by gpuente** [comment]
@GimpMaster can you share the full list of changes that you made? I'm trying to setup a common folder to share some code between the electron app and the react app but I got a lot of different errors
