### ISSUE TITLE
vite static assets does not work in build

### ISSUE THREAD

**Issue by rapiz1** [electron-vite/electron-vite-react#84]
https://vitejs.dev/guide/assets.html#importing-asset-as-url does not work in the build because URLs are not the same in dev and prod. And that's the root cause of https://github.com/electron-vite/electron-vite-react/issues/78
https://github.com/electron-vite/electron-vite-react/commit/71dd5078d99a8dacab297433de894e101307d286 is a hack to fix that.

However,

Something like`./electron.png` is actually not valid usage for vite. It's neither via `public` nor via dynamic import. It just happens to work in dev and prod because of the particular route of `App.tsx`.

The *valid* way to do this in vite is to use `/electron.png`. But that does not work in this boilerplate because the URL is not handled correctly.

**Comment by caoxiemeihao** [comment]
Do you still prefer to use the files in the public directory?
e.g. `import foo from '/foo.png'`

This will only work with browsers based on the http protocol.
And Node.js can only use relative paths, absolute paths, bare modules
`. /module` or `/User/name/module` or `module`.

In other words, if the public path (`/foo.png`) is used, is this required? It can't be replaced by other means?

**Comment by rapiz1** [comment]
On Saturday, 12 November 2022 21:29:04 CST 草鞋没号 wrote:
> Do you still prefer to use the files in the public directory?
> e.g. `import foo from '/foo.png'`
> 
> This will only work with browsers based on the http protocol.
> And Node.js can only use relative paths, absolute paths, bare modules
> `. /module` or `/User/name/module` or `module`.
> 
> In other words, if the public path (`/foo.png`) is used, is this required?
> It can't be replaced by other means?


Sorry for not making my point clear.

I think the evil is the inconsistency. You can write down a vanilla vite usage  
and see everything is good in `yarn dev` while everything booms in `yarn 
build`. dev and prod should have the same behaviour or the dev preview is 
meaningless.

BTW, `import foo from './assets/foo.png'` will not work as expected in prod. 
The image will be packed into `dist/assets/foo.xxxx.png`, but the imported URL 
will be somewhere under `dist`, not `dist/assets`.

**Comment by caoxiemeihao** [comment]
`electron-vite-react` changes Vite default behaviors?
