### ISSUE TITLE
Firebase: Error (auth/network-request-failed).

### ISSUE THREAD

**Issue by ivanandresdiaz** [electron-vite/electron-vite-react#85]
I am trying to use electron-vite-react ts template. But I have an error when I try to authenticate with firebase. I fill my credentials right, 

I use the method of SDK :

```
import { signInWithEmailAndPassword } from "firebase/auth";

  const handleLogin = () => {
    const data = getValues();
    setIsLoading(true);
    if (data.email && data.password) {
      signInWithEmailAndPassword(auth, data.email, data.password)
        .then((cred) => {
          setIsLoading(false);
          console.log("user logged in:", cred);
        })
        .catch((err) => {
          console.log("error", err);
// throws the error here. Firebase: Error (auth/network-request-failed)
          setIsLoading(false);
          console.log(err.message);
        });
    }
  };

```
 
throws the error: 

**Firebase: Error (auth/network-request-failed)**

I was watching the console and see the Request and response. And the **server of firebase/auth validate correctly the use**r. But I don't get the data in the Frontend.  So I would think this is a **vite problem**. But I don't understand how could I solve it. 

I have the repository here if you want to download it. 
https://github.com/ivanandresdiaz/vite-electron-firebase

**Comment by caoxiemeihao** [comment]
You can try Pre-Bundling `firebase/auth`
https://github.com/electron-vite/vite-plugin-electron/blob/14684ba108beec305edf4c9d8865527f6508f987/examples/nodeIntegration/vite.config.ts#L17-L26

```js
    renderer({
      optimizeDeps: {
        include: [
          'firebase/auth',
        ],
      },
    }),
```
