### ISSUE TITLE
How to use electron playwright with electron-vite-react

### ISSUE THREAD

**Issue by lifeiscontent** [electron-vite/electron-vite-react#86]
do you know how to setup electron playwright so we can do e2e tests for electron apps with this boilerplate? :)

**Comment by lifeiscontent** [comment]
@caoxiemeihao I previously had this working, but in a recent update to the boilerplate it broke :|

**Comment by lifeiscontent** [comment]
you can take a look here: https://github.com/BitGo/wallet-recovery-wizard

**Comment by lifeiscontent** [comment]
I think I've found the root of the issue,

there's some command called `startup` which launches electron, the same can be seen here: https://playwright.dev/docs/api/class-electron

I think we would need to stop `startup` from running during playwright tests, however I'm not sure what to pass to playwright for launch options, I've tried `['.', '--no-sandbox']` but that doesn't seem to work as I'd expect, do you have any thoughts?

**Comment by lifeiscontent** [comment]
I've managed to get it to work, but in order to run the tests, I have to first run a build, and then run playwright, it'd be nice if I could rely on the vite dev server instead, so if you have some ideas, please share. Happy to create a PR with the work I've done already to set it up as a default (if wanted)

**Comment by caoxiemeihao** [comment]
Great🎉
Looking forward to your PR.
Thx in advanced :)

**Comment by lifeiscontent** [comment]
@caoxiemeihao do you have any thoughts on how to get it to work with vite dev server rather than the built version?

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-plugin-electron/blob/1571a62b0a0c3df74b8144d509635dc9e77effb9/src/index.ts#L8
<img width="771" alt="image" src="https://user-images.githubusercontent.com/26263658/207260978-edcd51dd-44f9-497a-b718-e508e461b3b6.png">
https://github.com/electron-vite/vite-plugin-electron/blob/1571a62b0a0c3df74b8144d509635dc9e77effb9/src/index.ts#L41-L61
<img width="605" alt="image" src="https://user-images.githubusercontent.com/26263658/207261159-a79f2aac-2af4-4990-aff1-6eae528a96d5.png">
Perhaps it would be more appropriate to use `build`, `startup` which are two completely separate programmable APIs that  `npm run build` ultimately calls.

**Comment by lifeiscontent** [comment]
Hmm, I'm not sure how this would help, do you think you'd be willing to help me figure out the issues if I opened a PR that you could run locally within electron-vite-react? once I have the PR up, together we can figure out the issues and get it merged so others can use playwright to write tests easily.

What do you think @caoxiemeihao ?

**Comment by caoxiemeihao** [comment]
Yep! I'm happy to work with you :)

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-react/pull/100
