### ISSUE TITLE
Jetbrains Debugging - PhpStorm, Webstorm, etc

### ISSUE THREAD

**Issue by GimpMaster** [electron-vite/electron-vite-react#87]
Do you have any idea on how you can get the debugging for the Node side to work in phpstorm or webstorm?

It successfully launches the program but I can't breakpoint any of the electron side.

**Comment by GimpMaster** [comment]
I was able to successfully debug the node.js side by doing the following.

1. For the Run / Debug configuration I run Node (not NPM) and run this file. `.vscode\.debug.script.mjs`
2. I had to disable the vite-electron customStart by commenting out the following lines in vite.config.ts

        // ...(process.env.VSCODE_DEBUG
        //   ? [
        //     // Will start Electron via VSCode Debug
        //     customStart(debounce(() => console.log(/* For `.vscode/.debug.script.mjs` */'[startup] Electron App'))),
        //   ]
        //   : []),

After that I can set breakpoints in main/index.tsx and it works great.

**Comment by caoxiemeihao** [comment]
You can find a way to inject `process.env.VSCODE_DEBUG`
<img width="538" alt="image" src="https://user-images.githubusercontent.com/26263658/203487155-42d96038-650f-4665-b384-4db6114d7422.png">
When the `customStart` plugin is provided, it is possible to disable autostart without doing anything else.
```js
plugins: [customStart()],
```
