### ISSUE TITLE
Error no such file dirctory while yarn dev

### ISSUE THREAD

**Issue by lexxa-tech** [electron-vite/electron-vite-react#94]
Hello, i just following the Getting Started section, but when i write npm run dev, it shows an error
ENOENT: no such file or directory, stat 'C:/Users/ASUS/Documents/GitHub/snipsnap-electron/preload'

![image](https://user-images.githubusercontent.com/68645489/209602483-524baee2-2197-4479-a222-e5c73ddd84c5.png)

**Comment by caoxiemeihao** [comment]
Can you provide minimal reproduction repo?

**Comment by lexxa-tech** [comment]
It works after reinstalling node modules. Weird but i don't know it works
