### ISSUE TITLE
How to use ESM modules in main process? Dynamic import broken after build

### ISSUE THREAD

**Issue by johnlindquist** [electron-vite/electron-vite-react#98]
I'm just trying to use `execa` in the main process with:

```js
import { execaCommand } from "execa"
```

But I hit the `Error [ERR_REQUIRE_ESM]: require() of ES Module` issue.

---

If I switch to a dynamic import:

```js
const { execaCommand } = await import("execa")
```

This works fine with `npm run dev`, BUT breaks when building with `npm run build` with the following error:

(I'm using [electron-unhandled](https://github.com/sindresorhus/electron-unhandled) to capture the error)

```
Error: ENOTDIR: not a directory, stat '/Users/johnlindquist/dev/electron-vite-react/release/2.1.0/mac-arm64/electron-vite-react.app/Contents/Resources/app.asar/dist-electron/main/node_modules/execa'
```

Thanks for any help!

**Comment by caoxiemeihao** [comment]
@johnlindquist Hi 👋 
I am glad to receive your email and I will reply to your question here.
---
```
import { execaCommand } from "execa"
```
Is this used in the Renderer process? If so make sure you have enabled `nodeIntegration`.
https://github.com/electron-vite/electron-vite-react/blob/dfa51dd15541e9b181a09014bb74dabd1a82f2a6/electron/main/index.ts#L52-L53

**Comment by johnlindquist** [comment]
No, it's used in the main process.

**Comment by caoxiemeihao** [comment]
https://github.com/johnlindquist/kitapp/tree/vite
Can this repo reproduce the problem? I will Debug it.

**Comment by johnlindquist** [comment]
@caoxiemeihao I really just need dynamic imports to work.

It worked with my previous webpack config. It works with this in dev mode.

But the problem is when I run `npm run build`, it can't find a dynamic import.

**Comment by johnlindquist** [comment]
@caoxiemeihao You can easily reproduce with this fork here of electron-vite-react here:

All I added was:
```
  const { execaCommand } = await import("execa")
  await execaCommand(`say "Hello, Electron"`)
```

You'll see:
1. `npm run dev` works fine
2. `npm run build` breaks when you open the .app

https://github.com/johnlindquist/electron-vite-react

**Comment by caoxiemeihao** [comment]
I can try to get the ESM module to work under normal import. It will take me a little time.

**Comment by johnlindquist** [comment]
Thanks!

Is dynamic import an easy fix? I'd be happy to use that for now (it's what I used before with webpack).

**Comment by caoxiemeihao** [comment]
This is not difficult, I solved this problem in `vite-plugin-electron-renderer` before this.

**Comment by johnlindquist** [comment]
I just remembered, I need dynamic imports to work because I dynamically install/load "node-mac-permissions" only if the user is on mac.

**Comment by caoxiemeihao** [comment]
`vite-electron-plugin@0.7.x` is out!
This provides an example of using execa based on `0.7.x` 👉 [esmodule](https://github.com/electron-vite/vite-electron-plugin/tree/main/examples/esmodule)

**Comment by johnlindquist** [comment]
Thank you! Confirmed that sync imports are working. 👍

---

### Please fix `npm run build` with dynamic imports too... 🙏

I need `await import('node-mac-permissions')` to work so I can load it based on the users' operating system.

Steps to reproduce:

1. Use a dynamic import anywhere: 
```
await import('execa')
```
2. Run `npm run build`
3. Open the electron-vite-react.app

You'll get this error:

```
Error: ENOTDIR: not a directory, stat '/Users/johnlindquist/dev/electron-vite-react-dynamic-import/release/2.1.0/mac-arm64/electron-vite-react.app/Contents/Resources/app.asar/dist-electron/main/node_modules/execa'
```

**Comment by caoxiemeihao** [comment]
You just move `node-mac-permissions` to `dependencies` 😄

**Comment by johnlindquist** [comment]
It doesn't work after "npm run build" though

**Comment by caoxiemeihao** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/26263658/210122794-d156767c-64b4-442d-8345-313f2e6529cf.png">
`import()` is natively supported in Electron Main (since this API runs in the cjs module), so we just need to make sure that execa is built correctly into `app.asar`.

**Comment by caoxiemeihao** [comment]
`vite-electron-plugin@0.7.2` is out. Support dynamic `import()`!

**Comment by johnlindquist** [comment]
@caoxiemeihao Awesome, you rock! 🤘

I'll try this tomorrow, been AFK a couple days.

**Comment by johnlindquist** [comment]
vite-electron-plugin@0.7.2 is breaking for me. It hangs on this line. I have to "force quit" from activity monitor to get it to stop:

![CleanShot 2023-01-05 at 14 37 37](https://user-images.githubusercontent.com/36073/210884850-73d39779-4438-4a07-9a9a-2ef7e0bd3bbf.png)

The project is on the `vite` branch of this: https://github.com/johnlindquist/kitapp/tree/vite

0.7.1 builds fine.

**Comment by caoxiemeihao** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/26263658/210917514-33a860db-e46e-426d-8702-8a240d4a3a12.png">
On my local machine, v0.7.2 works fine 👀

**Comment by johnlindquist** [comment]
@caoxiemeihao Can you think of any way to debug this? The `--debug` flag isn't giving me any info


https://user-images.githubusercontent.com/36073/210919220-b96da314-93ef-4a61-a4f4-e034beac8069.mp4

**Comment by johnlindquist** [comment]
I tried a new checkout from iTerm this time:

```bash
git clone git@github.com:johnlindquist/kitapp.git kitapp-copy
cd kitapp-copy
npm i vite-electron-plugin@0.7.2
npm run build
```

Still hangs in the same spot each time:

![CleanShot 2023-01-05 at 19 53 39](https://user-images.githubusercontent.com/36073/210920365-bfa41f6b-995d-479b-88ee-4df6e41caead.png)

**Comment by johnlindquist** [comment]
0.7.2 also caused my CI to hang in the same spot. I cancelled after 38 minutes (it usually takes ~13 minutes):

![CleanShot 2023-01-05 at 21 05 35](https://user-images.githubusercontent.com/36073/210927996-c7e19c8b-2929-47ce-acb2-bd55e4f270a0.png)

**Comment by caoxiemeihao** [comment]
Upgrade `vite-electron-plugin` to `v0.7.3`
https://github.com/electron-vite/vite-electron-plugin/pull/51/commits/5a4c8db70e70399fd07b9c9c323c1e627bacc80e
This is an error from acorn and I don't know why it hangs. 🤔
```diff
- acorn.parse(code, { ecmaVersion: 'latest' })
+ acorn.parse(code, { ecmaVersion: 2022 })
```

**Comment by johnlindquist** [comment]
@caoxiemeihao Awesome, thanks for hunting that down 💛

**Comment by xiaomo1q** [comment]
`npm run build` It always stays here for a long time. The packaging is unsuccessful. Is it a version problem?
![image](https://user-images.githubusercontent.com/55676359/224608000-50bfb54e-c568-4d01-ba9a-8e2024d9661d.png)

**Comment by xiaomo1q** [comment]
`Invalid configuration object. electron-builder 23.6.0 has been initialized using a configuration object that does not match the API schema.` macos  build error

**Comment by caoxiemeihao** [comment]
@xiaomo1q 
1. Create `.npmrc` in your project.
2. Add proxy config for `electron`

```sh
electron_mirror=https://npmmirror.com/mirrors/electron/
```

> 这种简单问题多百度百度，问问题最好分类，不要在不相干的 issues 中问不相干的问题
